[package]
name = "codehelion-artifact-elf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "ELF artifact parser backend for codehelion."

[dependencies]
codehelion-artifact = { version = "0.1.0", path = "../codehelion-artifact" }
iced-x86 = { version = "1.21", default-features = false, features = ["std", "decoder"] }
object = { version = "0.39", default-features = false, features = ["read", "elf"] }

[dev-dependencies]
object = { version = "0.39", default-features = false, features = ["write", "elf"] }
proptest = "1.6"
serde_json = "1"

[lints]
workspace = true
