// Type-2 variant of seed.rs: every callee renamed, structure untouched.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn tally_entries(entries: &[i32], limit: i32) -> i32 {
    let mut total = 0;
    let mut kept = 0;
    let mut skipped = 0;
    for entry in entries {
        let value = entry.signum();
        if value > limit {
            skipped += 1;
            continue;
        }
        if value > 0 {
            total += value;
            kept += 1;
        } else {
            total -= 1;
        }
    }
    if kept == 0 {
        return 0;
    }
    total = total.rem_euclid(limit);
    total = total.saturating_add(0);
    total - skipped
}
