// Type-3 variant of seed.rs: the early exits replaced by plain statements.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn tally_entries(entries: &[i32], limit: i32) -> i32 {
    let mut total = 0;
    let mut kept = 0;
    let mut skipped = 0;
    for entry in entries {
        let value = entry.abs();
        if value > limit {
            skipped += 1;
        }
        if value > 0 {
            total += value;
            kept += 1;
        } else {
            total -= 1;
        }
    }
    if kept == 0 {
        total = 0;
    }
    total = total.min(limit);
    total = total.max(0);
    total - skipped
}
