// Type-3 variant of seed.rs: an inner loop nested inside the existing one.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn tally_entries(entries: &[i32], limit: i32) -> i32 {
    let mut total = 0;
    let mut kept = 0;
    let mut skipped = 0;
    for entry in entries {
        let value = entry.abs();
        if value > limit {
            skipped += 1;
            continue;
        }
        if value > 0 {
            total += value;
            for _ in 0..value {
                kept += 1;
            }
            kept += 1;
        } else {
            total -= 1;
        }
    }
    if kept == 0 {
        return 0;
    }
    total = total.min(limit);
    total = total.max(0);
    total - skipped
}
