// Type-3 variant of seed.rs: control flow and call surface both disturbed.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn tally_entries(entries: &[i32], limit: i32) -> i32 {
    let mut total = 0;
    let mut kept = 0;
    let mut skipped = 0;
    for entry in entries {
        let value = entry.signum();
        if value == limit {
            kept += 1;
            continue;
        }
        if value > limit {
            skipped += 1;
        }
        if value > 0 {
            total += value;
            for _ in 0..value {
                kept += 1;
            }
            kept += 1;
        } else {
            total -= 1;
        }
    }
    if kept == 0 {
        total = 0;
    }
    total = total.rem_euclid(limit);
    total = total.saturating_add(0);
    total - skipped
}
