//! Which program a run starts is the operator's decision, never the scanned
//! tree's.
//!
//! A compiler helper is started as a child process, so a setting that names one
//! is a setting that chooses code to execute. These run the real binary against
//! a tree that plants an executable beside a configuration pointing at it, and
//! watch for the one observable a spawn leaves behind: a file the planted
//! program writes when it runs.
//!
//! Unix only, because the observation needs a program a tree could plausibly
//! carry — an executable script. Windows starts no such file, so a tree there
//! cannot demonstrate the difference the tests are about.
#![cfg(unix)]
#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

use std::path::Path;

use assert_cmd::Command;

/// The environment variable the planted program writes when it is started.
const MARKER: &str = "CODEHELION_TEST_PLANTED_HELPER_MARKER";

fn cmd() -> Command {
    Command::cargo_bin("codehelion").expect("binary should build")
}

/// A small Rust project that names a program of its own as both helpers.
///
/// The location is relative, the way anything a repository writes about itself
/// is: it resolves against the directory the command is run in, which is this
/// tree.
fn tree_naming_its_own_program() -> tempfile::TempDir {
    use std::os::unix::fs::PermissionsExt as _;

    let directory = tempfile::tempdir().expect("temporary tree");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"planted\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write manifest");
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"planted\"\nversion = \"0.1.0\"\n",
    )
    .expect("write lockfile");
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn total(values: &[u64]) -> u64 { values.iter().sum() }\n",
    )
    .expect("write source");

    let payload = root.join("payload");
    std::fs::write(&payload, format!("#!/bin/sh\n: > \"${MARKER}\"\nexit 1\n"))
        .expect("write the planted program");
    std::fs::set_permissions(&payload, std::fs::Permissions::from_mode(0o755))
        .expect("make the planted program startable");

    std::fs::write(
        root.join("codehelion.toml"),
        "[helpers]\nrust = \"./payload\"\nclang = \"./payload\"\n",
    )
    .expect("write the tree's configuration");
    directory
}

/// Run one command in `root` with a marker of its own, and report whether the
/// planted program ran and what the command said on standard error.
fn run(root: &Path, marker_name: &str, arguments: &[&str]) -> (bool, String, String) {
    let marker = root.join(marker_name);
    let output = cmd()
        .current_dir(root)
        .env(MARKER, &marker)
        .args(arguments)
        .output()
        .unwrap_or_else(|error| panic!("running {arguments:?}: {error}"));
    (
        marker.exists(),
        String::from_utf8_lossy(&output.stdout).into_owned(),
        String::from_utf8_lossy(&output.stderr).into_owned(),
    )
}

/// Everything below rests on a spawn being visible, so this is the control: the
/// same program, named by the operator, does run. A marker that never appears
/// would make the other tests agree with an observation they cannot make.
#[test]
fn a_program_the_operator_names_is_started() {
    let tree = tree_naming_its_own_program();
    let (started, _, _) = run(
        tree.path(),
        "named-by-the-operator.marker",
        &["doctor", "--path", ".", "--helper", "rust=./payload"],
    );
    assert!(
        started,
        "a helper named on the command line was not started, so nothing below can observe one"
    );
}

/// `doctor` looks for helpers before it reports on them, and the tree's own
/// configuration is not one of the places it may look.
#[test]
fn doctor_does_not_start_a_program_the_scanned_tree_named() {
    let tree = tree_naming_its_own_program();
    let (started, report, stderr) = run(tree.path(), "doctor.marker", &["doctor", "--path", "."]);
    assert!(
        !started,
        "doctor started a program the scanned tree named as its helper"
    );
    assert!(
        stderr.contains("ignoring [helpers]"),
        "doctor disregarded the section without saying so: {stderr}"
    );
    assert!(
        !report.contains("payload"),
        "doctor reported the tree's program as a helper: {report}"
    );

    let (started, _, _) = run(
        tree.path(),
        "untrusted-doctor.marker",
        &["doctor", "--path", ".", "--untrusted"],
    );
    assert!(
        !started,
        "doctor --untrusted started a program the scanned tree named as its helper"
    );
}

/// Semantic mode shakes hands with every helper it can find before it reads a
/// file, which is the earliest point a configured location could be acted on.
#[test]
fn a_semantic_scan_does_not_start_a_program_the_scanned_tree_named() {
    let tree = tree_naming_its_own_program();
    let (started, _, stderr) = run(
        tree.path(),
        "scan.marker",
        &["scan", ".", "--mode", "semantic", "--format", "json"],
    );
    assert!(
        !started,
        "a semantic scan started a program the scanned tree named as its helper"
    );
    assert!(
        stderr.contains("ignoring [helpers]"),
        "the scan disregarded the section without saying so: {stderr}"
    );

    let (started, _, _) = run(
        tree.path(),
        "untrusted-scan.marker",
        &[
            "scan",
            ".",
            "--mode",
            "semantic",
            "--untrusted",
            "--format",
            "json",
        ],
    );
    assert!(
        !started,
        "a semantic scan of an untrusted tree started a program that tree named as its helper"
    );
}
