//! Semantic scan integration tests, run against the real compiler helpers.
//!
//! These exercise the complete process boundary and the `SQLite` persistence
//! path. They are ordinary tests: a workspace run builds both helper binaries
//! beside the CLI, `rust-toolchain.toml` installs the sysroot sources the Rust
//! helper reads, and libclang is loaded at run time. Nothing here is reserved
//! for CI — a check that only one machine ever performs is a check nobody is
//! keeping.

#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

use std::path::{Path, PathBuf};

use assert_cmd::Command;
use codehelion_eval::detected;
use codehelion_eval::labels::LabelSet;
use codehelion_eval::metrics::{DEFAULT_MATCH_THRESHOLD, evaluate, evaluate_by_rule};
use codehelion_store::Store;
use codehelion_store::compiler::CompilerOutcome;
use serde_json::Value;

fn cmd() -> Command {
    Command::cargo_bin("codehelion").expect("binary should build")
}

/// Write the lockfile that belongs to the manifest already in `root`.
///
/// A Rust fixture is analysed only after the helper proves the tree resolves
/// without a registry, and a manifest with no lockfile is the one shape that
/// proof cannot be made for offline. The package name is read back out of the
/// manifest rather than passed in, so a fixture cannot be added with a lockfile
/// that names something else — or with none at all.
fn lock_manifest(root: &Path) {
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).expect("read fixture manifest");
    let package = manifest
        .lines()
        .find_map(|line| line.trim().strip_prefix("name = "))
        .map(|name| name.trim().trim_matches('"'))
        .expect("fixture manifest names a package");
    std::fs::write(
        root.join("Cargo.lock"),
        format!(
            "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"{package}\"\nversion = \"0.1.0\"\n"
        ),
    )
    .expect("write lockfile");
}

fn scan(root: &Path) -> Value {
    scan_mode(root, "semantic")
}

fn scan_mode(root: &Path, mode: &str) -> Value {
    let output = cmd()
        .current_dir(root)
        .args(["scan", ".", "--mode", mode, "--format", "json"])
        .output()
        .expect("run semantic scan");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    serde_json::from_slice(&output.stdout).expect("semantic scan emits JSON")
}

fn scan_comparing_languages(root: &Path) -> Value {
    let output = cmd()
        .current_dir(root)
        .args([
            "scan",
            ".",
            "--mode",
            "semantic",
            "--format",
            "json",
            "--compare-languages",
        ])
        .output()
        .expect("run cross-language semantic scan");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    serde_json::from_slice(&output.stdout).expect("cross-language scan emits JSON")
}

/// The cross-language comparison a report carries, or why it is not there.
///
/// A scan that was asked to compare and could not says so, with the reason and
/// the compiler coverage behind it. Reading the absent key as "no comparison"
/// discards exactly the sentence that explains the run, which on a machine
/// whose standard library or helper answered less than the fixture needs is
/// the whole of the diagnosis.
fn cross_language_comparison(report: &Value) -> &serde_json::Map<String, Value> {
    report["cross_language_comparison"]
        .as_object()
        .unwrap_or_else(|| {
            let coverage: Vec<_> = report["partitions"]
                .as_array().map_or_else(|| vec![&report["summary"]["compiler"]], |partitions| {
                    partitions
                        .iter()
                        .map(|partition| &partition["summary"]["compiler"])
                        .collect()
                });
            panic!(
                "the scan produced no cross-language comparison.\nstatus: {}\ncompiler coverage per partition: {coverage:?}",
                report["cross_language_comparison_status"],
            )
        })
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("the CLI crate is two levels below the repository root")
        .to_path_buf()
}

/// The committed Rust corpus as a small Cargo library, with label paths made
/// relative to its actual source root. Semantic mode needs Cargo metadata;
/// the corpus itself intentionally remains build-system independent.
fn semantic_rust_corpus() -> (tempfile::TempDir, LabelSet) {
    let directory = tempfile::tempdir().expect("temporary Rust corpus");
    let root = directory.path();
    let source = repository_root().join("corpus/synthetic/rust");
    std::fs::create_dir_all(root.join("src")).expect("create corpus source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-corpus\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write corpus manifest");
    lock_manifest(root);
    for name in ["type1.rs", "type2.rs", "type3.rs"] {
        std::fs::copy(source.join(name), root.join("src").join(name))
            .unwrap_or_else(|error| panic!("copying corpus {name}: {error}"));
    }
    std::fs::copy(source.join("seed.rs"), root.join("src/lib.rs"))
        .expect("copy corpus seed as the library root");
    std::fs::write(
        root.join("src/lib.rs"),
        format!(
            "{}\nmod type1;\nmod type2;\nmod type3;\n",
            std::fs::read_to_string(root.join("src/lib.rs")).expect("read corpus library root")
        ),
    )
    .expect("wire corpus variants into the library");

    let labels_text =
        std::fs::read_to_string(source.join("labels.json")).expect("read committed corpus labels");
    let mut labels = LabelSet::from_json(&labels_text).expect("parse committed corpus labels");
    let source_path = |file: &mut String| {
        *file = if file == "seed.rs" {
            "src/lib.rs".to_owned()
        } else {
            format!("src/{file}")
        };
    };
    for file in &mut labels.files {
        source_path(file);
    }
    for pair in &mut labels.clone_pairs {
        for fragment in &mut pair.fragments {
            source_path(&mut fragment.file);
        }
    }
    for pair in &mut labels.non_clones {
        for fragment in &mut pair.fragments {
            source_path(&mut fragment.file);
        }
    }
    (directory, labels)
}

/// A hand-labelled Rust corpus for every initially registered same-language
/// semantic rule. It is intentionally kept separate from the generated
/// structural corpus because compiler-resolved constructs, rather than text
/// mutations, define its ground truth.
fn restricted_semantic_rust_corpus() -> (tempfile::TempDir, LabelSet) {
    let directory = tempfile::tempdir().expect("temporary restricted semantic corpus");
    let root = directory.path();
    let source = repository_root().join("corpus/synthetic/rust-restricted-semantic");
    std::fs::create_dir_all(root.join("src")).expect("create corpus source directory");
    for relative in ["Cargo.toml", "src/lib.rs", "labels.json"] {
        std::fs::copy(source.join(relative), root.join(relative)).unwrap_or_else(|error| {
            panic!("copying restricted semantic corpus {relative}: {error}")
        });
    }
    lock_manifest(root);
    let labels = LabelSet::from_json(
        &std::fs::read_to_string(root.join("labels.json"))
            .expect("read restricted semantic corpus labels"),
    )
    .expect("parse restricted semantic corpus labels");
    (directory, labels)
}

/// A hand-labelled C++ corpus for the closed standard-library serialization
/// rule. The compilation database supplies the parse settings without ever
/// executing a build command.
fn restricted_semantic_cpp_corpus() -> (tempfile::TempDir, LabelSet) {
    let directory = tempfile::tempdir().expect("temporary C++ restricted semantic corpus");
    let root = directory.path();
    let source = repository_root().join("corpus/synthetic/cpp-restricted-semantic");
    std::fs::create_dir_all(root.join("cpp")).expect("create corpus C++ source directory");
    std::fs::copy(source.join("cpp/direct.cpp"), root.join("cpp/direct.cpp"))
        .expect("copy restricted C++ semantic corpus source");
    let labels_text =
        std::fs::read_to_string(source.join("labels.json")).expect("read C++ corpus labels");
    let labels = LabelSet::from_json(&labels_text).expect("parse C++ corpus labels");
    let mut arguments = vec![
        "clang++".to_owned(),
        "-std=c++17".to_owned(),
        "-c".to_owned(),
        "cpp/direct.cpp".to_owned(),
    ];
    arguments.extend(cpp_standard_library_arguments());
    let database = serde_json::json!([{
        "directory": root.display().to_string(),
        "file": "cpp/direct.cpp",
        "arguments": arguments,
    }]);
    std::fs::write(
        root.join("compile_commands.json"),
        serde_json::to_string(&database).expect("compile database is JSON"),
    )
    .expect("write C++ corpus compilation database");
    (directory, labels)
}

/// A hand-labelled C++ corpus for the direct range-for forms admitted by the
/// sequence rule. The compilation database supplies parse settings only; the
/// scanner neither builds nor executes this source.
fn restricted_semantic_cpp_loop_corpus() -> (tempfile::TempDir, LabelSet) {
    let directory = tempfile::tempdir().expect("temporary C++ loop semantic corpus");
    let root = directory.path();
    let source = repository_root().join("corpus/synthetic/cpp-loop-restricted-semantic");
    std::fs::create_dir_all(root.join("cpp")).expect("create corpus C++ source directory");
    std::fs::copy(
        source.join("cpp/range_loop.cpp"),
        root.join("cpp/range_loop.cpp"),
    )
    .expect("copy restricted C++ loop corpus source");
    let labels_text =
        std::fs::read_to_string(source.join("labels.json")).expect("read C++ loop corpus labels");
    let labels = LabelSet::from_json(&labels_text).expect("parse C++ loop corpus labels");
    let mut arguments = vec![
        "clang++".to_owned(),
        "-std=c++17".to_owned(),
        "-c".to_owned(),
        "cpp/range_loop.cpp".to_owned(),
    ];
    arguments.extend(cpp_standard_library_arguments());
    let database = serde_json::json!([{
        "directory": root.display().to_string(),
        "file": "cpp/range_loop.cpp",
        "arguments": arguments,
    }]);
    std::fs::write(
        root.join("compile_commands.json"),
        serde_json::to_string(&database).expect("compile database is JSON"),
    )
    .expect("write C++ loop corpus compilation database");
    (directory, labels)
}

fn rust_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary Rust project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn total(values: &[u64]) -> u64 { values.iter().sum() }\n",
    )
    .expect("write Rust source");
    directory
}

/// A real compiler-backed pipeline pair. The predicates differ, so this is
/// not a text clone claim; the registered rule deliberately compares only the
/// resolved source/filter/collect operation sequence.
fn rust_pipeline_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary Rust pipeline project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-pipeline-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn odds(values: &[u64]) -> Vec<u64> {\n    values.iter().filter(|value| **value % 2 == 1).map(|value| *value).collect()\n}\n\npub fn evens(values: &[u64]) -> Vec<u64> {\n    values.iter().filter(|value| **value % 2 == 0).map(|value| *value).collect()\n}\n",
    )
    .expect("write Rust pipeline source");
    directory
}

/// A C++ standard-library serialization pair and a nearby non-pair. The
/// compile database is written only for the helper; nothing in this fixture is
/// compiled or run by the scan.
fn cpp_serialization_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary C++ serialization project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("cpp")).expect("create C++ source directory");
    std::fs::write(
        root.join("cpp/direct.cpp"),
        "#include <string>\n\nunsigned long long first(unsigned long long value) {\n    const auto text = std::to_string(value);\n    return std::stoull(text);\n}\n\nunsigned long long second(unsigned long long value) {\n    const auto text = std::to_string(value);\n    return std::stoull(text);\n}\n\nstd::size_t formats_twice(unsigned long long value) {\n    return (std::to_string(value) + std::to_string(value)).size();\n}\n",
    )
    .expect("write C++ serialization source");
    let mut arguments = vec![
        "clang++".to_owned(),
        "-std=c++17".to_owned(),
        "-c".to_owned(),
        "cpp/direct.cpp".to_owned(),
    ];
    arguments.extend(cpp_standard_library_arguments());
    let database = serde_json::json!([{
        "directory": root.display().to_string(),
        "file": "cpp/direct.cpp",
        "arguments": arguments
    }]);
    std::fs::write(
        root.join("compile_commands.json"),
        serde_json::to_string(&database).expect("compile database is JSON"),
    )
    .expect("write compilation database");
    directory
}

/// Two registered iterator pipelines embedded in larger functions. The
/// presence checks deliberately sit outside the sequence rule's vocabulary,
/// so a semantic finding must report only the pipeline source range.
fn rust_partial_pipeline_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary partial pipeline project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-partial-pipeline-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn odds(values: &[u64], keep: Option<u64>) -> Vec<u64> {\n    let collected: Vec<_> = values.iter().filter(|value| **value % 2 == 1).map(|value| *value).collect();\n    if keep.is_some() { collected } else { Vec::new() }\n}\n\npub fn evens(values: &[u64], keep: Option<u64>) -> Vec<u64> {\n    let collected: Vec<_> = values.iter().filter(|value| **value % 2 == 0).map(|value| *value).collect();\n    if keep.is_some() { collected } else { Vec::new() }\n}\n",
    )
    .expect("write Rust source");
    directory
}

/// A compiler-backed pair whose only registered correspondence is an explicit
/// standard-`Vec` collection loop and a plain iterator collection pipeline.
fn rust_loop_pipeline_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary Rust loop-pipeline project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-loop-pipeline-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn explicit<'a>(values: &'a [u64]) -> Vec<&'a u64> {\n    let mut collected = Vec::new();\n    for value in values {\n        collected.push(value);\n    }\n    collected\n}\n\npub fn iterator<'a>(values: &'a [u64]) -> Vec<&'a u64> {\n    values.iter().collect()\n}\n",
    )
    .expect("write Rust source");
    directory
}

/// Two reductions that share only the compiler-resolved iterator source and
/// fold operations. Their accumulator expressions deliberately differ.
fn rust_reduce_pipeline_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary Rust reduce project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-reduce-pipeline-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn sum(values: &[u64]) -> u64 {\n    values.iter().fold(0, |total, value| total + value)\n}\n\npub fn product(values: &[u64]) -> u64 {\n    values.iter().fold(1, |total, value| total * value)\n}\n",
    )
    .expect("write Rust reduce pipelines");
    directory
}

/// Direct arithmetic accumulation over one standard sequence, paired with an
/// iterator reduction. The guarded control must remain outside the closed
/// loop form because it no longer reduces every element.
fn rust_loop_reduce_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary loop-reduce project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-loop-reduce-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn explicit(values: &[u64]) -> u64 {\n    let mut total = 0;\n    for value in values {\n        total += *value;\n    }\n    total\n}\n\npub fn iterator(values: &[u64]) -> u64 {\n    values.iter().fold(0, |total, value| total + *value)\n}\n\npub fn guarded(values: &[u64]) -> u64 {\n    let mut total = 0;\n    for value in values {\n        if *value > 0 {\n            total += *value;\n        }\n    }\n    total\n}\n",
    )
    .expect("write Rust source");
    directory
}

/// Three lexical standard-file lifetimes. `unwrap` keeps the fixture free of a
/// propagation construct, so the registered resource rule sees only the
/// compiler-resolved acquisition and the function-scope `Drop`.
fn rust_resource_lifetime_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary Rust resource project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-resource-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn inspect_first(path: &std::path::Path) {\n    let _file = std::fs::File::open(path).unwrap();\n}\n\npub fn inspect_second(path: &std::path::Path) {\n    let _file = std::fs::File::open(path).unwrap();\n}\n\npub fn inspect_third(path: &std::path::Path) {\n    let _file = std::fs::File::open(path).unwrap();\n}\n",
    )
    .expect("write Rust resource source");
    directory
}

/// Direct `Result` and `Option` adapter pairs whose only semantic
/// correspondences are the closed propagation forms. The transformed forms
/// are negative controls: they must not be treated as identity adapters.
fn rust_direct_propagation_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary direct propagation project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-direct-result-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn operator(value: Result<u64, ()>) -> Result<u64, ()> {\n    Ok(value?)\n}\n\npub fn branches(value: Result<u64, ()>) -> Result<u64, ()> {\n    match value {\n        Ok(value) => Ok(value),\n        Err(error) => Err(error),\n    }\n}\n\npub fn transformed(value: Result<u64, ()>) -> Result<u64, ()> {\n    let value = value?;\n    Ok(value.saturating_add(1))\n}\n\npub fn option_operator(value: Option<u64>) -> Option<u64> {\n    Some(value?)\n}\n\npub fn option_branches(value: Option<u64>) -> Option<u64> {\n    match value {\n        Some(value) => Some(value),\n        None => None,\n    }\n}\n\npub fn option_transformed(value: Option<u64>) -> Option<u64> {\n    Some(value?.saturating_add(1))\n}\n\nmod project_lookalike {\n    #[allow(non_snake_case)]\n    fn Some(value: u64) -> Option<u64> {\n        Option::Some(value)\n    }\n\n    pub fn project_named_some(value: Option<u64>) -> Option<u64> {\n        Some(value?)\n    }\n}\n",
    )
    .expect("write Rust source");
    directory
}

/// Direct standard-`Option` presence checks, a match, and two narrow early
/// unit-return guards. Compound conditions and non-returning/value-returning
/// negative branches remain outside the closed validation operation.
fn rust_optional_validation_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary optional validation project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-optional-validation-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn first(value: Option<u64>) -> bool {\n    if value.is_some() {\n        true\n    } else {\n        false\n    }\n}\n\npub fn second(value: Option<u64>) -> bool {\n    if value.is_some() {\n        false\n    } else {\n        true\n    }\n}\n\npub fn matched(value: Option<u64>) -> bool {\n    match value {\n        Some(_) => true,\n        None => false,\n    }\n}\n\npub fn early_first(value: Option<u64>) {\n    if !value.is_some() {\n        return;\n    }\n    let _ = value;\n}\n\npub fn early_second(value: Option<u64>) {\n    if !value.is_some() {\n        return;\n    }\n    let _ = value;\n}\n\npub fn compound(value: Option<u64>, keep: bool) -> bool {\n    if value.is_some() && keep {\n        true\n    } else {\n        false\n    }\n}\n\npub fn negative_nonreturn(value: Option<u64>) {\n    if !value.is_some() {\n        let _ = value;\n    }\n}\n\npub fn negative_value_return(value: Option<u64>) -> Option<u64> {\n    if !value.is_some() {\n        return None;\n    }\n    value\n}\n",
    )
    .expect("write Rust source");
    directory
}

/// Two direct standard-`Result` presence checks, plus compound and project
/// lookalike negatives. Only the compiler-resolved standard method may enter
/// the closed validation rule.
fn rust_result_validation_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary result validation project");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"semantic-result-validation-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write Rust manifest");
    lock_manifest(root);
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn first(value: Result<u64, ()>) -> bool {\n    if value.is_ok() {\n        true\n    } else {\n        false\n    }\n}\n\npub fn second(value: Result<u64, ()>) -> bool {\n    if value.is_ok() {\n        false\n    } else {\n        true\n    }\n}\n\npub fn compound(value: Result<u64, ()>, keep: bool) -> bool {\n    if value.is_ok() && keep {\n        true\n    } else {\n        false\n    }\n}\n\nstruct Lookalike;\n\nimpl Lookalike {\n    fn is_ok(&self) -> bool {\n        true\n    }\n}\n\nfn lookalike(value: Lookalike) -> bool {\n    if value.is_ok() {\n        true\n    } else {\n        false\n    }\n}\n",
    )
    .expect("write Rust source");
    directory
}

/// One Rust pipeline and one manually ported C++ pipeline. They share only
/// the closed source/collection correspondence; their source text and build
/// variants are intentionally independent.
fn cross_language_pipeline_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary cross-language project");
    let root = directory.path();
    let corpus = repository_root().join("corpus/synthetic/rust-cpp-semantic");
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::create_dir_all(root.join("cpp")).expect("create C++ source directory");
    for relative in ["Cargo.toml", "src/lib.rs", "cpp/copied.cpp", "labels.json"] {
        std::fs::copy(corpus.join(relative), root.join(relative))
            .unwrap_or_else(|error| panic!("copying cross-language corpus {relative}: {error}"));
    }
    lock_manifest(root);
    let mut arguments = vec!["clang++".to_string(), "-std=c++17".to_string()];
    arguments.extend(cpp_standard_library_arguments());
    arguments.extend(["-c".to_string(), "cpp/copied.cpp".to_string()]);
    let database = serde_json::json!([{
        "directory": root.display().to_string(),
        "file": "cpp/copied.cpp",
        "arguments": arguments
    }]);
    std::fs::write(
        root.join("compile_commands.json"),
        serde_json::to_string(&database).expect("compile database is JSON"),
    )
    .expect("write compilation database");
    directory
}

/// Rust and C++ direct loops whose correspondence is established by the
/// compiler-confirmed construct form, not an inferred or invented API name.
fn cross_language_direct_loop_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary cross-language loop project");
    let root = directory.path();
    let corpus = repository_root().join("corpus/synthetic/rust-cpp-loop-semantic");
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::create_dir_all(root.join("cpp")).expect("create C++ source directory");
    for relative in [
        "Cargo.toml",
        "src/lib.rs",
        "cpp/range_loop.cpp",
        "labels.json",
    ] {
        std::fs::copy(corpus.join(relative), root.join(relative)).unwrap_or_else(|error| {
            panic!("copying cross-language loop corpus {relative}: {error}")
        });
    }
    lock_manifest(root);
    let mut arguments = vec!["clang++".to_string(), "-std=c++17".to_string()];
    arguments.extend(cpp_standard_library_arguments());
    arguments.extend(["-c".to_string(), "cpp/range_loop.cpp".to_string()]);
    let database = serde_json::json!([{
        "directory": root.display().to_string(),
        "file": "cpp/range_loop.cpp",
        "arguments": arguments,
    }]);
    std::fs::write(
        root.join("compile_commands.json"),
        serde_json::to_string(&database).expect("compile database is JSON"),
    )
    .expect("write compilation database");
    directory
}

/// A Rust `Result` adapter and the closed C++23 `expected` identity-return
/// counterpart. Their only cross-language relationship is the registered
/// propagation correspondence; the C++ function has no API-call sequence to
/// borrow a pipeline match from.
fn cross_language_result_expected_fixture() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("temporary result/expected project");
    let root = directory.path();
    let corpus = repository_root().join("corpus/synthetic/rust-cpp-result-expected-semantic");
    std::fs::create_dir_all(root.join("src")).expect("create Rust source directory");
    std::fs::create_dir_all(root.join("cpp")).expect("create C++ source directory");
    for relative in ["Cargo.toml", "src/lib.rs", "cpp/direct.cpp", "labels.json"] {
        std::fs::copy(corpus.join(relative), root.join(relative))
            .unwrap_or_else(|error| panic!("copying result/expected corpus {relative}: {error}"));
    }
    lock_manifest(root);
    // `c++2b` rather than `c++23`: the fixture needs `<expected>`, and the
    // oldest Clang this project reads a project with does not recognise the
    // final spelling of the standard that introduced it. Both spellings select
    // the same standard on every Clang that accepts either.
    let mut arguments = vec!["clang++".to_string(), "-std=c++2b".to_string()];
    arguments.extend(cpp_standard_library_arguments());
    arguments.extend(["-c".to_string(), "cpp/direct.cpp".to_string()]);
    let database = serde_json::json!([{
        "directory": root.display().to_string(),
        "file": "cpp/direct.cpp",
        "arguments": arguments
    }]);
    std::fs::write(
        root.join("compile_commands.json"),
        serde_json::to_string(&database).expect("compile database is JSON"),
    )
    .expect("write compilation database");
    directory
}

/// The project fixture renderer adds this flag on macOS because Clang does not
/// discover Xcode's C++ headers from an arbitrary compilation database.
fn cpp_standard_library_arguments() -> Vec<String> {
    if !cfg!(target_os = "macos") {
        return Vec::new();
    }
    let configured = std::env::var_os("SDKROOT").map(PathBuf::from);
    let sdk = configured.into_iter().chain([
        PathBuf::from("/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"),
        PathBuf::from("/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"),
    ]).find(|path| path.is_dir());
    sdk.and_then(|path| path.to_str().map(str::to_string))
        .map_or_else(Vec::new, |path| vec!["-isysroot".to_string(), path])
}

fn stored_ir(root: &Path, run_id: i64) -> bool {
    Store::open(&root.join(".codehelion/audit.db"))
        .expect("open audit database")
        .run_compiler_units(run_id)
        .expect("read compiler IR")
        .iter()
        .any(|unit| matches!(unit.outcome, CompilerOutcome::Analyzed(_)))
}

/// A Semantic scan emits a restricted-semantic finding only after the real
/// Rust helper supplies resolved API calls, and persists both normalized
/// graphs and the registered-rule evidence beside the ordinary snapshot.
#[path = "semantic_helpers/compiler_evidence.rs"]
mod compiler_evidence;
#[path = "semantic_helpers/golden_and_safety.rs"]
mod golden_and_safety;
#[path = "semantic_helpers/registered_rules.rs"]
mod registered_rules;
