// Type-3 variant of seed.rs with ~10% of its statements replaced in place.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn summarise(samples: &[i32]) -> i32 {
    let mut total = 0;
    let mut spread = 0;
    let mut peak = 0;
    let mut dips = 0;
    for sample in samples {
        let value = *sample;
        total += value;
        if value > peak {
            peak = value;
        }
        if value < 0 {
            dips += 1;
        }
        spread += value + value;
    }
    let width = samples.len() as i32;
    total -= dips;
    total += spread / 4;
    total += peak;
    total -= width;
    total
}
