//! Detection of machine-generated files.
//!
//! Generated files are excluded before any clone candidate is produced: they
//! duplicate their generator's templates, not hand-written logic, so reporting
//! them as clones is noise. Detection is a marker scan over the file's first
//! lines; the marker set is configurable so a project can add its own
//! generator's banner.

/// Markers recognised by default in a generated file's header.
pub const DEFAULT_MARKERS: &[&str] = &["@generated", "DO NOT EDIT", "Code generated by"];

/// Number of leading lines scanned for a marker by default.
pub const DEFAULT_SCAN_LINES: usize = 20;

/// A configured set of generated-file markers.
#[derive(Debug, Clone)]
pub struct GeneratedMarkers {
    markers: Vec<String>,
    scan_lines: usize,
}

impl Default for GeneratedMarkers {
    fn default() -> Self {
        Self {
            markers: DEFAULT_MARKERS.iter().map(|m| (*m).to_string()).collect(),
            scan_lines: DEFAULT_SCAN_LINES,
        }
    }
}

impl GeneratedMarkers {
    /// Build a marker set from explicit markers and a scan depth.
    #[must_use]
    pub const fn new(markers: Vec<String>, scan_lines: usize) -> Self {
        Self {
            markers,
            scan_lines,
        }
    }

    /// The default markers plus `extra`, keeping the default scan depth.
    #[must_use]
    pub fn with_additional(extra: &[String]) -> Self {
        let mut markers: Vec<String> = DEFAULT_MARKERS.iter().map(|m| (*m).to_string()).collect();
        markers.extend(extra.iter().cloned());
        Self {
            markers,
            scan_lines: DEFAULT_SCAN_LINES,
        }
    }

    /// Whether the head of a file marks it as generated.
    ///
    /// `head` should be the file's leading text; only the first configured
    /// number of lines is inspected.
    #[must_use]
    pub fn is_generated(&self, head: &str) -> bool {
        head.lines()
            .take(self.scan_lines)
            .any(|line| self.markers.iter().any(|marker| line.contains(marker)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_markers_match_common_banners() {
        let markers = GeneratedMarkers::default();
        assert!(markers.is_generated("// @generated by prost\nfn a() {}"));
        assert!(markers.is_generated("/* DO NOT EDIT */\n"));
        assert!(markers.is_generated("// Code generated by protoc. DO NOT EDIT."));
    }

    #[test]
    fn hand_written_files_are_not_generated() {
        let markers = GeneratedMarkers::default();
        assert!(!markers.is_generated("//! A normal module.\nfn real() {}"));
    }

    #[test]
    fn markers_past_the_scan_window_are_ignored() {
        let markers = GeneratedMarkers::new(vec!["@generated".to_string()], 2);
        let head = "line1\nline2\n// @generated\n";
        assert!(!markers.is_generated(head));
    }

    #[test]
    fn additional_markers_extend_the_defaults() {
        let markers = GeneratedMarkers::with_additional(&["AUTOGENERATED".to_string()]);
        assert!(markers.is_generated("# AUTOGENERATED FILE\n"));
        assert!(markers.is_generated("// @generated\n"));
    }
}
