//! The shipped JSON schemas and the documents they accept.

use super::*;

#[test]
#[allow(
    clippy::too_many_lines,
    reason = "one schema test keeps the complete current, legacy-additive, and invalid sibling contracts together"
)]
fn current_json_report_validates_against_the_shipped_schema() {
    let schema: serde_json::Value = serde_json::from_str(JSON_SCHEMA).unwrap();
    let mut schemas = Schemas::new();
    let mut compiler = Compiler::new();
    let uri = "https://github.com/libraz/codehelion/blob/main/crates/codehelion-cli/schema/scan-report-v2.schema.json";
    compiler.add_resource(uri, schema).unwrap();
    let index = compiler.compile(uri, &mut schemas).unwrap();
    let value: serde_json::Value =
        serde_json::from_str(&sample_report().to_json().unwrap()).unwrap();
    schemas.validate(&value, index).unwrap();

    let mut unrecorded = sample_report();
    unrecorded.run.run_id = None;
    unrecorded.run.reused = false;
    unrecorded.summary.changes = None;
    let unrecorded: serde_json::Value =
        serde_json::from_str(&unrecorded.to_json().unwrap()).unwrap();
    schemas.validate(&unrecorded, index).unwrap();

    let mut with_execution_refusal = sample_report();
    with_execution_refusal.summary.compiler = Some(CompilerCoverage {
        answered: 0,
        not_asked: 0,
        not_asked_reasons: BTreeMap::new(),
        unavailable: BTreeMap::from([("requires_execution".to_string(), 1)]),
        diagnostics: BTreeMap::new(),
        execution_refusals: vec![ExecutionRefusal {
            execution: "build-script".to_string(),
            files: 1,
            cost: "types generated by a build script".to_string(),
            permission_argument: "--allow-execution=build-script".to_string(),
            message: "Pass --allow-execution=build-script to allow it.".to_string(),
        }],
        restarts: 0,
    });
    let with_execution_refusal: serde_json::Value =
        serde_json::from_str(&with_execution_refusal.to_json().unwrap()).unwrap();
    schemas.validate(&with_execution_refusal, index).unwrap();

    let mut report = sample_report();
    report.near_misses = vec![sample_near_miss()];
    report.groups.push(structural_group());
    report.groups[2]
        .similarity
        .as_mut()
        .expect("sample structural group has similarity evidence")
        .confidence_band = None;
    let without_a_recorded_band: serde_json::Value =
        serde_json::from_str(&report.to_json().unwrap()).unwrap();
    schemas.validate(&without_a_recorded_band, index).unwrap();

    // The additive fields remain optional for reports emitted before sibling
    // provenance was persisted.
    let mut old_v1_report = sample_report();
    old_v1_report.siblings = vec![sample_siblings()];
    old_v1_report.summary.guardrails = Some(Guardrails {
        profile: "untrusted".to_string(),
        max_file_bytes: 1,
        parse_timeout_ms: 2,
        helper_timeout_ms: 3,
        posting_cap: 4,
        pair_budget: 5,
        verification_budget: Some(6),
        max_alignment_cells: Some(7),
        near_miss_delta: Some(0.1),
        near_miss_cap: Some(8),
        sibling_candidate_budget: Some(9),
        sibling_per_group_cap: Some(10),
        sibling_total_cap: Some(11),
        signature_sibling_candidate_budget: Some(12),
        signature_sibling_per_group_cap: Some(13),
        signature_sibling_total_cap: Some(14),
        signature_sibling_max_units_per_signature: Some(16),
        max_component: Some(15),
    });
    let mut old_v1: serde_json::Value =
        serde_json::from_str(&old_v1_report.to_json().unwrap()).unwrap();
    let old_sibling = old_v1["siblings"][0]["siblings"][0]
        .as_object_mut()
        .expect("sibling object");
    old_sibling.remove("basis");
    old_sibling.remove("signature");
    let old_guardrails = old_v1["summary"]["guardrails"]
        .as_object_mut()
        .expect("guardrails object");
    old_guardrails.remove("signature_sibling_candidate_budget");
    old_guardrails.remove("signature_sibling_per_group_cap");
    old_guardrails.remove("signature_sibling_total_cap");
    old_guardrails.remove("signature_sibling_max_units_per_signature");
    schemas.validate(&old_v1, index).unwrap();

    let mut signature_report = sample_report();
    let mut signature_group = sample_siblings();
    signature_group.siblings[0].basis = "signature".to_string();
    signature_group.siblings[0].signature = Some("schema-signature".to_string());
    signature_report.siblings = vec![signature_group];
    let signature_value: serde_json::Value =
        serde_json::from_str(&signature_report.to_json().unwrap()).unwrap();
    schemas.validate(&signature_value, index).unwrap();

    let mut missing_signature = signature_value;
    missing_signature["siblings"][0]["siblings"][0]
        .as_object_mut()
        .expect("sibling object")
        .remove("signature");
    assert!(schemas.validate(&missing_signature, index).is_err());

    let null_signature: serde_json::Value =
        serde_json::from_str(&signature_report.to_json().unwrap()).unwrap();
    let mut null_signature = null_signature;
    null_signature["siblings"][0]["siblings"][0]["signature"] = serde_json::Value::Null;
    assert!(schemas.validate(&null_signature, index).is_err());

    let mut orphan_signature = value.clone();
    orphan_signature["siblings"] = serde_json::json!([{
        "group_fingerprint": "0b".repeat(16),
        "siblings": [{
            "clone_type": "type-3",
            "confidence_band": "low",
            "signature": "orphan-signature",
            "similarity": {
                "weight_version": "structural-verify-v1",
                "lexical": 0.72,
                "structural": 0.91,
                "control_flow": 0.8,
                "type_similarity": null,
                "api": 0.7,
                "composite": 0.76
            },
            "member": {
                "finding_id": "f0".repeat(16),
                "content": "f1".repeat(16),
                "file": "src/incomplete.rs",
                "language": "rust",
                "start_line": 30,
                "end_line": 36,
                "unit": "incomplete_checksum",
                "tokens": 31,
                "canonical": false
            },
            "suppressed": null
        }]
    }]);
    assert!(schemas.validate(&orphan_signature, index).is_err());

    let mut similarity_with_signature = value.clone();
    similarity_with_signature["siblings"] = serde_json::json!([{
        "group_fingerprint": "0b".repeat(16),
        "siblings": [{
            "clone_type": "type-3",
            "confidence_band": "low",
            "basis": "similarity",
            "signature": "must-not-be-present",
            "similarity": {
                "weight_version": "structural-verify-v1",
                "lexical": 0.72,
                "structural": 0.91,
                "control_flow": 0.8,
                "type_similarity": null,
                "api": 0.7,
                "composite": 0.76
            },
            "member": {
                "finding_id": "f0".repeat(16),
                "content": "f1".repeat(16),
                "file": "src/incomplete.rs",
                "language": "rust",
                "start_line": 30,
                "end_line": 36,
                "unit": "incomplete_checksum",
                "tokens": 31,
                "canonical": false
            },
            "suppressed": null
        }]
    }]);
    assert!(schemas.validate(&similarity_with_signature, index).is_err());

    let mut unsupported = value;
    unsupported["schema_version"] = serde_json::json!(3);
    assert!(schemas.validate(&unsupported, index).is_err());
}

#[test]
fn group_boilerplate_schema_tracks_the_classifier_categories() {
    let schema: serde_json::Value = serde_json::from_str(JSON_SCHEMA).unwrap();
    let values = schema["$defs"]["group"]["properties"]["boilerplate"]["enum"]
        .as_array()
        .expect("group boilerplate enum");
    let categories: Vec<_> = values
        .iter()
        .filter_map(serde_json::Value::as_str)
        .collect();
    let expected: Vec<_> = Boilerplate::all()
        .iter()
        .map(|category| category.name())
        .collect();
    assert_eq!(categories, expected);
    assert!(
        values.iter().any(serde_json::Value::is_null),
        "a group without a dominant shape remains representable"
    );
}

#[test]
fn restricted_semantic_evidence_is_explicit_in_json() {
    let mut report = sample_report();
    let group = &mut report.groups[0];
    group.clone_type = "restricted-semantic".to_string();
    group.semantic = Some(SemanticEvidence {
        schema_version: "sog-v1".to_string(),
        rules: vec![SemanticRuleEvidence {
            id: "sequence-pipeline-v1".to_string(),
            version: 1,
            confidence: 0.7,
        }],
        graphs: vec![semantic_graph(), semantic_graph()],
        node_mappings: vec![SemanticNodeMapping {
            corresponding_member: 1,
            canonical: 0,
            corresponding: 0,
        }],
    });
    let value: serde_json::Value = serde_json::from_str(&report.to_json().unwrap()).unwrap();
    assert_eq!(
        value["groups"][0]["semantic"]["rules"][0]["id"],
        "sequence-pipeline-v1"
    );
    assert_eq!(
        value["groups"][0]["semantic"]["graphs"]
            .as_array()
            .map(Vec::len),
        Some(2)
    );
    let schema: serde_json::Value = serde_json::from_str(JSON_SCHEMA).unwrap();
    assert!(schema["$defs"]["group"]["properties"]["semantic"].is_object());
    assert!(schema["$defs"]["semantic_evidence"].is_object());
}

#[test]
#[allow(
    clippy::too_many_lines,
    reason = "the test walks every public JSON object against its schema declaration"
)]
fn json_field_names_appear_in_the_shipped_schema() {
    let schema: serde_json::Value = serde_json::from_str(JSON_SCHEMA).unwrap();
    assert_eq!(
        schema["properties"]["schema_version"]["const"],
        i64::from(SCHEMA_VERSION)
    );
    assert_eq!(schema["properties"]["summary"]["$ref"], "#/$defs/summary");
    assert!(schema["$defs"]["run"]["properties"]["configuration"].is_object());
    assert!(
        schema["$defs"]["summary"]["properties"]["compiler"]["properties"]["execution_refusals"]
            .is_object()
    );
    let mut report = sample_report();
    report.groups.push(structural_group());
    report.groups.push(fragment_group());
    report.summary.baseline = Some(BaselineStatus {
        file: "codehelion-baseline.json".to_string(),
        entries: 12,
        mode: BASELINE_SUPPRESS.to_string(),
        matched: 11,
        stale: 1,
        appeared: 3,
        expanded: 0,
        expanded_instances: 0,
        stale_tokens: 320,
        appeared_tokens: 90,
        expanded_tokens: 0,
        gone: vec![GoneGroup {
            group: "aa11".to_string(),
            clone_type: "type-2".to_string(),
            duplicated_tokens: 320,
            anchor: Some(GoneAnchor {
                file: "src/gone.rs".to_string(),
                start_line: 10,
                end_line: 40,
                unit: Some("validate".to_string()),
            }),
        }],
    });
    report.siblings = vec![sample_siblings()];
    report.seam = Some(sample_seam_report());
    report.groups[0].identity = Some(GroupIdentity {
        origin: IDENTITY_ADOPTED.to_string(),
        compared_with_run: 1,
        adopted_from: Some("ab".repeat(16)),
        shared_members: Some(2),
        compared_members: Some(3),
    });
    report.groups[0].baseline = Some(GroupBaseline {
        state: GROUP_NEW.to_string(),
        added_instances: None,
        derived_from: Some(Derivation {
            group: "aa11".to_string(),
            shared_sites: 2,
        }),
    });
    let value: serde_json::Value = serde_json::from_str(&report.to_json().unwrap()).unwrap();
    assert!(value["groups"][0]["artifact_savings"].is_array());
    assert!(value["summary"]["search_truncated"].is_boolean());
    let baseline_schema = &schema["$defs"]["summary"]["properties"]["baseline"]["properties"];
    assert!(baseline_schema.get("mismatch").is_none());
    assert!(baseline_schema.get("caveat").is_none());
    let group_baseline_schema = &schema["$defs"]["group"]["properties"]["baseline"]["properties"];
    let run_schema = &schema["$defs"]["run"]["properties"];
    let run_configuration_schema =
        &schema["$defs"]["run"]["properties"]["configuration"]["properties"];
    let checks = [
        (&value["groups"][3], &schema["$defs"]["group"]["properties"]),
        (&value["summary"]["baseline"], baseline_schema),
        (
            &value["summary"]["baseline"]["gone"][0],
            &baseline_schema["gone"]["items"]["properties"],
        ),
        (
            &value["summary"]["baseline"]["gone"][0]["anchor"],
            &baseline_schema["gone"]["items"]["properties"]["anchor"]["properties"],
        ),
        (&value["groups"][0]["baseline"], group_baseline_schema),
        (
            &value["groups"][0]["baseline"]["derived_from"],
            &group_baseline_schema["derived_from"]["properties"],
        ),
        (&value, &schema["properties"]),
        (&value["run"], run_schema),
        (&value["run"]["configuration"], run_configuration_schema),
        (&value["summary"], &schema["$defs"]["summary"]["properties"]),
        (
            &value["summary"]["groups"],
            &schema["$defs"]["summary"]["properties"]["groups"]["properties"],
        ),
        (&value["groups"][0], &schema["$defs"]["group"]["properties"]),
        (
            &value["groups"][0]["members"][0],
            &schema["$defs"]["member"]["properties"],
        ),
        (
            &value["groups"][1]["suppressed"],
            &schema["$defs"]["suppression"]["properties"],
        ),
        (
            &value["groups"][2]["similarity"],
            &schema["$defs"]["similarity"]["properties"],
        ),
        (
            &value["run"]["ranking"],
            &schema["$defs"]["ranking"]["properties"],
        ),
        (
            &value["groups"][0]["priority"],
            &schema["$defs"]["priority"]["properties"],
        ),
        (
            &value["groups"][0]["priority"]["inputs"],
            &schema["$defs"]["priority_inputs"]["properties"],
        ),
        (
            &value["groups"][0]["identity"],
            &schema["$defs"]["group"]["properties"]["identity"]["properties"],
        ),
        (
            &value["siblings"][0],
            &schema["$defs"]["group_siblings"]["properties"],
        ),
        (
            &value["siblings"][0]["siblings"][0],
            &schema["$defs"]["sibling"]["properties"],
        ),
        (
            &value["siblings"][0]["siblings"][0]["similarity"],
            &schema["$defs"]["sibling_similarity"]["properties"],
        ),
        (&value["seam"], &schema["$defs"]["seam"]["properties"]),
        (
            &value["seam"]["seams"][0],
            &schema["$defs"]["reported_seam"]["properties"],
        ),
    ];
    for (object, properties) in checks {
        for key in object.as_object().unwrap().keys() {
            assert!(
                properties.get(key).is_some(),
                "field {key:?} missing from the shipped schema"
            );
        }
    }
}
