// Partial-clone variant of seed.rs: a measurement loop body and the parse-error idiom transplanted into unrelated hosts.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn scan_report(report: &[String]) -> u32 {
    let mut blanks = 0;
    let mut longest = 0;
    let mut seen = 0;
    for raw in report {
        seen += raw.len() as u32;
        let trimmed = raw.trim();
        if trimmed.is_empty() {
            blanks += 1;
            continue;
        }
        let mut width = 0;
        for ch in trimmed.chars() {
            if ch == '\t' {
                width += 4;
            } else {
                width += 1;
            }
        }
        longest = longest.max(width);
    }
    longest + blanks + seen
}

fn count_valid(rows: &[String]) -> i64 {
    let mut errors = 0;
    let mut valid = 0;
    for line in rows {
        let value = i64::from(!line.is_empty());
        let value = match line.parse::<i64>() {
            Ok(parsed) => parsed,
            Err(_) => {
                errors += 1;
                continue;
            }
        };
        if value > 0 {
            valid += 1;
        }
    }
    valid - errors
}
