// Partial-clone variant of seed.rs: a renamed checksum statement run and the parse-error idiom transplanted into unrelated hosts.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn merge_batches(entries: &[u64], state: &mut u64) -> u64 {
    let mut merged = 0;
    for entry in entries {
        merged += *entry;
    }
    merged ^= *state;
    let mut blend = 1;
    for entry in entries {
        blend = blend.rotate_left(9) ^ *entry;
        if blend == 0 {
            blend = 11;
        }
    }
    *state ^= blend;
    merged
}

fn sum_marked(rows: &[String]) -> i64 {
    let mut errors = 0;
    let mut sum = 0;
    for line in rows {
        let value = line.len() as i64;
        let value = match line.parse::<i64>() {
            Ok(parsed) => parsed,
            Err(_) => {
                errors += 1;
                continue;
            }
        };
        sum += value;
    }
    sum - errors
}
