// Type-1 variant of seed.rs: identical logic, only comments and spacing differ.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

// Adds up the even entries.
fn sum_even(values: &[i32]) -> i32 {
    let mut total = 0;

    for value in values {
        if value % 2 == 0 {
            total += value;
        }
    }
    total
}

// Longest run of consecutive true flags.
fn max_run(flags: &[bool]) -> usize {
    let mut best = 0;
    let mut current = 0;
    for flag in flags {
        if *flag {
            current += 1;
            if current > best {
                best = current;
            }
        } else {
            current = 0;
            // A false flag resets the run.
        }
    }
    best
}

// Compares two value sequences twice with index loops.
fn values_equal(left: &[i32], right: &[i32]) -> bool {
    if left.len() != right.len() {
        return false;
    }
    let mut left_index = 0;
    while left_index < left.len() {
        if left[left_index] != right[left_index] {
            return false;
        }
        left_index += 1;
    }
    let mut right_index = 0;
    while right_index < left.len() {
        if left[right_index] != right[right_index] {
            return false;
        }
        right_index += 1;
    }
    true
}
