[package]
name = "codehelion-artifact-pe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "PE and COFF artifact parser backend for codehelion."

[dependencies]
codehelion-artifact = { version = "0.1.0", path = "../codehelion-artifact" }
object = { version = "0.39", default-features = false, features = ["read", "coff", "pe"] }
pdb = "0.8"

[dev-dependencies]
object = { version = "0.39", default-features = false, features = ["write", "coff"] }
proptest = "1.6"

[lints]
workspace = true
