//! Configuration model, discovery and resolution.
//!
//! Configuration comes from three layers, highest precedence first: explicit
//! command-line flags, a `codehelion.toml` file, then built-in defaults. This
//! module owns the file layer and the defaults; each command applies its own
//! flag overrides on top of the [`Config`] it receives.
//!
//! The file is discovered by walking up from the scan directory to the
//! filesystem root and taking the first `codehelion.toml`. Unknown keys are
//! rejected so a typo surfaces as an error rather than being silently ignored.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// File name discovered by the upward search.
pub const CONFIG_FILE_NAME: &str = "codehelion.toml";

/// Literal-normalization strategy for Type-2 detection.
///
/// The default is [`Full`](LiteralNormalization::Full): the Phase 0 evaluation
/// found full normalization gives Type-2 recall 1.0.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum LiteralNormalization {
    /// Keep literal values distinct (normalize identifiers only).
    Preserve,
    /// Normalize literals by category (integer, float, string, char).
    Category,
    /// Normalize every literal to a single placeholder.
    #[default]
    Full,
}

/// Languages the scan analyses.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields, rename_all = "kebab-case")]
pub struct Languages {
    /// Analyse Rust sources.
    pub rust: bool,
    /// Analyse C sources.
    pub c: bool,
    /// Analyse C++ sources.
    pub cpp: bool,
}

impl Default for Languages {
    fn default() -> Self {
        Self {
            rust: true,
            c: true,
            cpp: true,
        }
    }
}

/// Minimal Phase-1 suppression settings.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields, rename_all = "kebab-case")]
pub struct Suppression {
    /// Path globs whose matches are excluded from findings.
    pub paths: Vec<String>,
    /// Markers that, when found in a file's first lines, flag it as generated
    /// and exclude it before candidate generation.
    pub generated_markers: Vec<String>,
}

impl Default for Suppression {
    fn default() -> Self {
        Self {
            paths: Vec::new(),
            generated_markers: vec![
                "@generated".to_string(),
                "DO NOT EDIT".to_string(),
                "Code generated by".to_string(),
            ],
        }
    }
}

/// Effective analysis configuration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields, rename_all = "kebab-case")]
pub struct Config {
    /// Path globs to include; empty means every supported source file.
    pub include: Vec<String>,
    /// Path globs to exclude from the include set.
    pub exclude: Vec<String>,
    /// Smallest clone length, in tokens, that is reported.
    pub min_clone_tokens: u32,
    /// Literal-normalization strategy.
    pub literal_normalization: LiteralNormalization,
    /// Languages to analyse.
    pub languages: Languages,
    /// Suppression settings.
    pub suppression: Suppression,
    /// Audit-database location, relative to the scan root unless absolute.
    pub database: PathBuf,
    /// Worker-thread count; `None` selects a count automatically.
    pub jobs: Option<usize>,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            include: Vec::new(),
            exclude: Vec::new(),
            // Phase 0 decision: k = 20-token effective minimum clone length.
            min_clone_tokens: 20,
            literal_normalization: LiteralNormalization::default(),
            languages: Languages::default(),
            suppression: Suppression::default(),
            database: PathBuf::from(".codehelion/audit.db"),
            jobs: None,
        }
    }
}

impl Config {
    /// Parse a [`Config`] from its TOML representation.
    ///
    /// # Errors
    ///
    /// Returns an error if the text is not valid TOML or contains an unknown
    /// key.
    pub fn from_toml(text: &str) -> Result<Self> {
        toml::from_str(text).context("parsing configuration")
    }

    /// Serialize this configuration to TOML.
    ///
    /// # Errors
    ///
    /// Returns an error if serialization fails (for example, a non-UTF-8
    /// database path).
    pub fn to_toml(&self) -> Result<String> {
        toml::to_string_pretty(self).context("serializing configuration")
    }
}

/// Where the resolved configuration came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConfigSource {
    /// Loaded from this file.
    File(PathBuf),
    /// No file found; built-in defaults were used.
    Defaults,
}

/// A resolved configuration together with its provenance.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedConfig {
    /// The effective configuration.
    pub config: Config,
    /// Where it came from.
    pub source: ConfigSource,
}

/// Resolve the configuration for a scan rooted at `start_dir`.
///
/// When `explicit` is given, that file is loaded and a missing or invalid file
/// is an error. Otherwise the first `codehelion.toml` found by walking up from
/// `start_dir` is used, falling back to defaults when none exists.
///
/// # Errors
///
/// Returns an error if a named or discovered file cannot be read or parsed.
pub fn load(explicit: Option<&Path>, start_dir: &Path) -> Result<ResolvedConfig> {
    if let Some(path) = explicit {
        let config = read_file(path)?;
        return Ok(ResolvedConfig {
            config,
            source: ConfigSource::File(path.to_path_buf()),
        });
    }
    match find_upward(start_dir) {
        Some(path) => {
            let config = read_file(&path)?;
            Ok(ResolvedConfig {
                config,
                source: ConfigSource::File(path),
            })
        }
        None => Ok(ResolvedConfig {
            config: Config::default(),
            source: ConfigSource::Defaults,
        }),
    }
}

fn read_file(path: &Path) -> Result<Config> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("reading configuration file {}", path.display()))?;
    Config::from_toml(&text).with_context(|| format!("in configuration file {}", path.display()))
}

/// Walk up from `start_dir` to the filesystem root, returning the first
/// `codehelion.toml` found.
fn find_upward(start_dir: &Path) -> Option<PathBuf> {
    let mut dir = Some(start_dir);
    while let Some(current) = dir {
        let candidate = current.join(CONFIG_FILE_NAME);
        if candidate.is_file() {
            return Some(candidate);
        }
        dir = current.parent();
    }
    None
}

/// A commented template written by `config init`, holding every key at its
/// default so it can be uncommented and edited.
pub const TEMPLATE: &str = "\
# codehelion configuration. Every key below shows its built-in default;
# uncomment and edit the ones you want to change.

# Path globs to include; empty means every supported source file.
# include = []
# Path globs to exclude from the include set.
# exclude = []

# Smallest clone length, in tokens, that is reported.
# min-clone-tokens = 20

# Literal-normalization strategy: \"preserve\", \"category\" or \"full\".
# literal-normalization = \"full\"

# Audit-database location, relative to the scan root unless absolute.
# database = \".codehelion/audit.db\"

# Worker-thread count; omit for automatic.
# jobs = 4

# [languages]
# rust = true
# c = true
# cpp = true

# [suppression]
# paths = []
# generated-markers = [\"@generated\", \"DO NOT EDIT\", \"Code generated by\"]
";

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn defaults_are_the_phase0_values() {
        let config = Config::default();
        assert_eq!(config.min_clone_tokens, 20);
        assert_eq!(config.literal_normalization, LiteralNormalization::Full);
        assert!(config.languages.rust && config.languages.c && config.languages.cpp);
        assert_eq!(config.database, PathBuf::from(".codehelion/audit.db"));
    }

    #[test]
    fn missing_keys_fall_back_to_defaults() {
        let config = Config::from_toml("min-clone-tokens = 30").unwrap();
        assert_eq!(config.min_clone_tokens, 30);
        // Untouched keys keep their defaults.
        assert_eq!(config.literal_normalization, LiteralNormalization::Full);
        assert!(config.languages.rust);
    }

    #[test]
    fn unknown_key_is_rejected() {
        let err = Config::from_toml("min_clone_tokens = 30")
            .expect_err("snake_case key is unknown; kebab-case is expected");
        assert!(format!("{err:#}").contains("unknown field"));
    }

    #[test]
    fn round_trips_through_toml() {
        let config = Config::default();
        let text = config.to_toml().unwrap();
        let back = Config::from_toml(&text).unwrap();
        assert_eq!(config, back);
    }

    #[test]
    fn template_parses_as_defaults() {
        // Every setting in the template is commented out, so it parses to an
        // empty table and resolves to the defaults.
        let config = Config::from_toml(TEMPLATE).unwrap();
        assert_eq!(config, Config::default());
    }

    #[test]
    fn explicit_missing_file_is_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let missing = dir.path().join("nope.toml");
        assert!(load(Some(&missing), dir.path()).is_err());
    }

    #[test]
    fn upward_search_finds_a_parent_config() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(CONFIG_FILE_NAME), "min-clone-tokens = 15").unwrap();
        let nested = dir.path().join("a/b");
        std::fs::create_dir_all(&nested).unwrap();
        let resolved = load(None, &nested).unwrap();
        assert_eq!(resolved.config.min_clone_tokens, 15);
        assert!(matches!(resolved.source, ConfigSource::File(_)));
    }

    #[test]
    fn no_file_resolves_to_defaults() {
        let dir = tempfile::tempdir().unwrap();
        let resolved = load(None, dir.path()).unwrap();
        assert_eq!(resolved.source, ConfigSource::Defaults);
        assert_eq!(resolved.config, Config::default());
    }
}
