// Signature mirror: same callable shape, deliberately rewritten control flow.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

int signature_mirror(const int *source, int count) {
    const int *cursor = source;
    const int *end = source + count;
    int result = 0;
    while (cursor != end) {
        if (cursor != end) {
            result += (*cursor % 2 == 0) ? *cursor : 0;
            ++cursor;
        }
    }
    return result;
}
