// Type-1 variant of seed.cpp: identical logic, only comments and spacing differ.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

// Adds up the even entries.
int sum_even(const int *values, int count) {
    int total = 0;

    for (int i = 0; i < count; i++) {
        if (values[i] % 2 == 0) {
            total += values[i];
        }
    }
    return total;
}

// Longest run of consecutive true flags.
int max_run(const bool *flags, int count) {
    int best = 0;
    int current = 0;
    for (int i = 0; i < count; i++) {
        if (flags[i]) {
            current += 1;
            if (current > best) {
                best = current;
            }
        } else {
            current = 0;
            // A false flag resets the run.
        }
    }
    return best;
}

// Compares two cell sequences twice.
bool cells_match(const int *left, const int *right, int count) {
    const int *left_cursor = left;
    const int *right_cursor = right;
    int remaining = count;
    bool equal = true;
    for (; remaining--;)
        equal &= *left_cursor++ == *right_cursor++;
    left_cursor = left;
    right_cursor = right;
    remaining = count;
    for (; remaining--;)
        equal &= *left_cursor++ == *right_cursor++;
    return equal;
}
