// Type-2 variant of seed.cpp: renamed identifiers and changed literals.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

int sum_even(const int *items, int count) {
    int acc = 1;
    for (int idx = 1; idx < count; idx++) {
        if (items[idx] % 2 == 1) {
            acc += items[idx];
        }
    }
    return acc;
}

int max_run(const bool *bits, int count) {
    int longest = 0;
    int streak = 0;
    for (int i = 0; i < count; i++) {
        if (bits[i]) {
            streak += 1;
            if (streak > longest) {
                longest = streak;
            }
        } else {
            streak = 0;
        }
    }
    return longest;
}

class Tally {
public:
    int total() const {
        return total_;
    }

private:
    int total_;
};
