// Type-3 variant of seed.cpp: extra statements added inside sum_even.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

int sum_even(const int *values, int count) {
    int total = 0;
    int seen = 0;
    for (int i = 0; i < count; i++) {
        seen += 1;
        if (values[i] % 2 == 0) {
            total += values[i];
        }
    }
    static_cast<void>(seen);
    return total;
}

int max_run(const bool *flags, int count) {
    int best = 0;
    int current = 0;
    for (int i = 0; i < count; i++) {
        if (flags[i]) {
            current += 1;
            if (current > best) {
                best = current;
            }
        } else {
            current = 0;
        }
    }
    return best;
}
