//! Variant emission, provenance-based range computation and label assembly.
//!
//! Rendering keeps, for every output line, the seed line it derives from (its
//! *provenance*). Label ranges are then computed from that mapping: a labelled
//! region's variant fragment spans the first to the last output line whose
//! provenance falls inside the region's seed range. Inserted lines between
//! mapped lines are covered by the span; comment lines inserted before an
//! item's header are not.
//!
//! Transplanted fragments ([`TransplantSpec`]) are tracked by insertion
//! identity instead: each transplant's lines carry the transplant's ordinal,
//! and its variant range spans the first to the last surviving line with that
//! ordinal. Provenance would be ambiguous here, because the donor item can be
//! carried into the same variant alongside the transplanted copy.

use std::collections::{BTreeMap, BTreeSet};

use crate::corpus::lexer::substitute;
use crate::corpus::scan::{Item, Language, brace_balance, scan_items};
use crate::corpus::spec::{
    EditOp, ItemSpec, MutationSpec, NonCloneSpec, TransplantSpec, VariantSpec,
};
use crate::corpus::{Error, LABEL_SCHEMA_VERSION, LABELS_FILE, SPEC_SCHEMA_VERSION};
use crate::eval::labels::{LabelPair, LabelSet, NonClone};
use crate::eval::schema::{CloneType, Fragment};

/// Marker comment emitted as the second line of every generated variant file.
pub const GENERATED_MARKER: &str =
    "// Generated by codehelion-corpus-gen; edit the mutation spec instead.";

/// Achieved statement-change rate for one type-3 item.
#[derive(Debug, Clone, PartialEq)]
pub struct ChangeRate {
    /// Variant file the item was rendered into.
    pub variant: String,
    /// Key of the mutated item.
    pub item: String,
    /// Rate declared in the spec, if any.
    pub target: Option<f64>,
    /// Statement lines inserted or deleted by the edits.
    pub changed_statements: u32,
    /// Statement lines in the seed item.
    pub total_statements: u32,
}

impl ChangeRate {
    /// Achieved rate: changed statements over the seed item's statement
    /// count, or `0.0` for an empty item.
    #[must_use]
    pub fn achieved(&self) -> f64 {
        if self.total_statements == 0 {
            0.0
        } else {
            f64::from(self.changed_statements) / f64::from(self.total_statements)
        }
    }
}

/// Everything the generator produces for one spec: the output files (variant
/// sources plus the label document) and the achieved change rates.
#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedCorpus {
    /// Output file name to exact file contents.
    pub files: BTreeMap<String, String>,
    /// The label document, also serialized into
    /// [`files`](Self::files) under [`LABELS_FILE`].
    pub labels: LabelSet,
    /// Achieved change rates for every type-3 item that declares a target or
    /// performs statement edits.
    pub change_rates: Vec<ChangeRate>,
}

/// One output line with the seed line it derives from, if any.
// `seed_line` is the clearest name for the originating seed line number, even
// though it ends with the struct name.
#[allow(clippy::struct_field_names)]
#[derive(Debug, Clone)]
struct Line {
    text: String,
    seed_line: Option<u32>,
    /// Ordinal of the transplant that inserted this line, if any, for
    /// fragment-range resolution after all edits.
    transplant: Option<usize>,
}

/// A rendered variant file before serialization.
struct RenderedVariant {
    file: String,
    lines: Vec<Line>,
}

/// A labelled region whose variant range is resolved after rendering.
struct PendingPair {
    variant_file: String,
    clone_type: CloneType,
    /// Item key the region belongs to (the donor key for a transplant), for
    /// error messages.
    item_key: String,
    seed_start: u32,
    seed_end: u32,
    /// When set, the variant fragment is the run of lines inserted by this
    /// transplant rather than the provenance-mapped item range.
    transplant: Option<usize>,
}

/// A transplant-derived non-clone whose variant range is resolved after
/// rendering.
struct PendingNonClone {
    variant_file: String,
    donor_key: String,
    reason: String,
    seed_start: u32,
    seed_end: u32,
    transplant: usize,
}

/// Labels collected while rendering, resolved once every variant is rendered.
#[derive(Default)]
struct PendingLabels {
    pairs: Vec<PendingPair>,
    non_clones: Vec<PendingNonClone>,
    /// Next transplant ordinal; unique across all variants of one spec.
    next_transplant: usize,
}

/// Shared read-only inputs for rendering one variant.
struct RenderContext<'a> {
    by_key: &'a BTreeMap<&'a str, &'a Item>,
    seed_lines: &'a [&'a str],
    variant_file: &'a str,
    default_type: CloneType,
}

fn to_usize(n: u32) -> usize {
    usize::try_from(n).unwrap_or(usize::MAX)
}

fn to_u32(n: usize) -> u32 {
    u32::try_from(n).unwrap_or(u32::MAX)
}

/// Whether a trimmed line counts as a statement under the controlled
/// one-statement-per-line style: non-blank, not a comment, and not led by a
/// closing brace (so `}` and `} else {` are structure, not statements).
/// `//` line comments are the only comment form in every supported language
/// (Rust, C, C++); `/* */` block comments are outside the controlled style
/// (see [`scan`](crate::corpus::scan)).
fn is_statement(trimmed: &str) -> bool {
    !trimmed.is_empty() && !trimmed.starts_with("//") && !trimmed.starts_with('}')
}

/// Generate every output file and the label document for `spec`.
///
/// `seed_text` is the contents of the spec's seed file. The result is fully
/// deterministic: the same inputs always produce byte-identical output.
///
/// # Errors
///
/// Returns an [`Error`] when the spec declares an unsupported language,
/// references unknown items or files, an edit cannot be applied, an edit is
/// not allowed for the item's clone type, or the label document cannot be
/// serialized.
pub fn generate(spec: &MutationSpec, seed_text: &str) -> Result<GeneratedCorpus, Error> {
    if spec.schema_version != SPEC_SCHEMA_VERSION {
        return Err(Error::UnsupportedSchemaVersion(spec.schema_version));
    }
    let language = Language::parse(&spec.language).ok_or_else(|| Error::UnsupportedLanguage {
        language: spec.language.clone(),
    })?;
    let items = scan_items(seed_text, language);
    let by_key = index_items(&items)?;
    let seed_lines: Vec<&str> = seed_text.lines().collect();

    let mut rendered = Vec::new();
    let mut change_rates = Vec::new();
    let mut pending = PendingLabels::default();
    for variant in &spec.variants {
        let ctx = RenderContext {
            by_key: &by_key,
            seed_lines: &seed_lines,
            variant_file: &variant.file,
            default_type: variant.clone_type,
        };
        rendered.push(render_variant(
            variant,
            &ctx,
            &mut change_rates,
            &mut pending,
        )?);
    }

    let mut files_list = vec![spec.seed.clone()];
    files_list.extend(spec.variants.iter().map(|variant| variant.file.clone()));
    let mut non_clones = resolve_non_clones(&spec.non_clones, &by_key, &rendered, &spec.seed)?;
    non_clones.extend(resolve_transplant_non_clones(
        &pending.non_clones,
        &rendered,
        &spec.seed,
        spec.non_clones.len(),
    )?);
    let labels = LabelSet {
        schema_version: LABEL_SCHEMA_VERSION,
        language: spec.language.clone(),
        files: files_list,
        clone_pairs: resolve_pairs(&pending.pairs, &rendered, &spec.seed)?,
        non_clones,
    };
    let files = collect_files(rendered, &labels)?;
    Ok(GeneratedCorpus {
        files,
        labels,
        change_rates,
    })
}

/// First 1-based line at which two texts differ, or `None` when identical.
#[must_use]
pub fn first_difference(expected: &str, actual: &str) -> Option<u32> {
    if expected == actual {
        return None;
    }
    let expected_lines: Vec<&str> = expected.split('\n').collect();
    let actual_lines: Vec<&str> = actual.split('\n').collect();
    for (index, (left, right)) in expected_lines.iter().zip(&actual_lines).enumerate() {
        if left != right {
            return Some(to_u32(index + 1));
        }
    }
    Some(to_u32(expected_lines.len().min(actual_lines.len()) + 1))
}

fn index_items(items: &[Item]) -> Result<BTreeMap<&str, &Item>, Error> {
    let mut map = BTreeMap::new();
    for item in items {
        if map.insert(item.key.as_str(), item).is_some() {
            return Err(Error::DuplicateItem {
                key: item.key.clone(),
            });
        }
    }
    Ok(map)
}

fn render_variant(
    variant: &VariantSpec,
    ctx: &RenderContext<'_>,
    change_rates: &mut Vec<ChangeRate>,
    pending: &mut PendingLabels,
) -> Result<RenderedVariant, Error> {
    let mut lines = vec![
        Line {
            text: format!("// {}", variant.header_comment),
            seed_line: None,
            transplant: None,
        },
        Line {
            text: GENERATED_MARKER.to_string(),
            seed_line: None,
            transplant: None,
        },
    ];
    let mut seen = BTreeSet::new();
    for item_spec in &variant.items {
        if !seen.insert(item_spec.item.as_str()) {
            return Err(Error::DuplicateItem {
                key: item_spec.item.clone(),
            });
        }
        let item = ctx
            .by_key
            .get(item_spec.item.as_str())
            .copied()
            .filter(|item| !item.nested)
            .ok_or_else(|| Error::UnknownItem {
                variant: variant.file.clone(),
                item: item_spec.item.clone(),
            })?;
        let effective = item_spec.clone_type.unwrap_or(variant.clone_type);
        validate_item(effective, ctx.default_type, &variant.file, item_spec)?;

        lines.push(Line {
            text: String::new(),
            seed_line: None,
            transplant: None,
        });
        if item_spec.labelled {
            pending.pairs.push(PendingPair {
                variant_file: variant.file.clone(),
                clone_type: effective,
                item_key: item_spec.item.clone(),
                seed_start: item.start_line,
                seed_end: item.end_line,
                transplant: None,
            });
        }
        let (mut item_lines, changed) = render_item(item_spec, item, ctx, pending)?;
        lines.append(&mut item_lines);

        if effective == CloneType::Type3 && (changed > 0 || item_spec.target_change_rate.is_some())
        {
            change_rates.push(ChangeRate {
                variant: variant.file.clone(),
                item: item_spec.item.clone(),
                target: item_spec.target_change_rate,
                changed_statements: changed,
                total_statements: count_statements(ctx.seed_lines, item),
            });
        }
    }
    Ok(RenderedVariant {
        file: variant.file.clone(),
        lines,
    })
}

fn validate_item(
    effective: CloneType,
    default_type: CloneType,
    variant: &str,
    item_spec: &ItemSpec,
) -> Result<(), Error> {
    if !matches!(
        effective,
        CloneType::Type1 | CloneType::Type2 | CloneType::Type3
    ) {
        return Err(Error::UnsupportedCloneType {
            variant: variant.to_string(),
        });
    }
    let disallowed = |reason: &str| {
        Err(Error::DisallowedEdit {
            variant: variant.to_string(),
            item: item_spec.item.clone(),
            reason: reason.to_string(),
        })
    };
    let has_substitution = !item_spec.rename.is_empty() || !item_spec.literals.is_empty();
    let has_statement_edit = item_spec.edits.iter().any(|edit| {
        matches!(
            edit,
            EditOp::InsertAfter { .. } | EditOp::InsertBefore { .. } | EditOp::Delete { .. }
        )
    });
    if effective == CloneType::Type1 && has_substitution {
        return disallowed(
            "type-1 allows whitespace and comment changes only; `rename`/`literals` require type-2",
        );
    }
    if effective != CloneType::Type3 {
        if has_statement_edit {
            return disallowed("statement insertion/deletion requires type-3");
        }
        if !item_spec.transplants.is_empty() {
            return disallowed("transplanting a fragment inserts statements and requires type-3");
        }
        if item_spec.target_change_rate.is_some() {
            return disallowed("`target_change_rate` requires type-3");
        }
    }
    for transplant in &item_spec.transplants {
        validate_transplant(transplant, default_type, variant, &item_spec.item)?;
    }
    Ok(())
}

/// Validate one transplant's label declaration against the effective-type
/// rules: a labelled transplant is type-1 (verbatim only) or type-2, and
/// `labelled` and `non_clone` are mutually exclusive.
fn validate_transplant(
    transplant: &TransplantSpec,
    default_type: CloneType,
    variant: &str,
    item: &str,
) -> Result<(), Error> {
    let disallowed = |reason: String| {
        Err(Error::DisallowedEdit {
            variant: variant.to_string(),
            item: item.to_string(),
            reason,
        })
    };
    if transplant.labelled && transplant.non_clone.is_some() {
        return disallowed(format!(
            "transplant from `{}` cannot be both `labelled` and a `non_clone`",
            transplant.donor
        ));
    }
    if !transplant.labelled {
        return Ok(());
    }
    let effective = transplant.clone_type.unwrap_or(default_type);
    let has_substitution = !transplant.rename.is_empty() || !transplant.literals.is_empty();
    match effective {
        CloneType::Type1 if has_substitution => disallowed(format!(
            "a type-1 transplant from `{}` must be verbatim; `rename`/`literals` require type-2",
            transplant.donor
        )),
        CloneType::Type1 | CloneType::Type2 => Ok(()),
        _ => disallowed(format!(
            "a labelled transplant from `{}` must be type-1 or type-2",
            transplant.donor
        )),
    }
}

/// Render one item: copy its seed lines with provenance, apply substitution,
/// apply the transplants, then apply the line edits in spec order. Returns
/// the lines and the number of statement lines inserted or deleted.
fn render_item(
    item_spec: &ItemSpec,
    item: &Item,
    ctx: &RenderContext<'_>,
    pending: &mut PendingLabels,
) -> Result<(Vec<Line>, u32), Error> {
    let needs_substitution = !item_spec.rename.is_empty() || !item_spec.literals.is_empty();
    let mut lines = Vec::new();
    for line_no in item.start_line..=item.end_line {
        if let Some(text) = ctx.seed_lines.get(to_usize(line_no).saturating_sub(1)) {
            let text = if needs_substitution {
                substitute(text, &item_spec.rename, &item_spec.literals)
            } else {
                (*text).to_string()
            };
            lines.push(Line {
                text,
                seed_line: Some(line_no),
                transplant: None,
            });
        }
    }
    let mut changed = 0;
    for transplant in &item_spec.transplants {
        changed += apply_transplant(&mut lines, transplant, &item_spec.item, ctx, pending)?;
    }
    for edit in &item_spec.edits {
        changed += apply_edit(&mut lines, edit, ctx.variant_file, &item_spec.item)?;
    }
    Ok((lines, changed))
}

/// Apply one transplant: copy the donor fragment out of the seed, apply the
/// transplant's substitutions, insert the lines after the host anchor and
/// queue the declared label. Returns the number of statement lines inserted.
fn apply_transplant(
    lines: &mut Vec<Line>,
    transplant: &TransplantSpec,
    host_key: &str,
    ctx: &RenderContext<'_>,
    pending: &mut PendingLabels,
) -> Result<u32, Error> {
    let donor = ctx
        .by_key
        .get(transplant.donor.as_str())
        .copied()
        .ok_or_else(|| Error::UnknownItem {
            variant: ctx.variant_file.to_string(),
            item: transplant.donor.clone(),
        })?;
    let from = find_seed_anchor(ctx, donor, &transplant.from)?;
    let to = find_seed_anchor(ctx, donor, &transplant.to)?;
    if from > to {
        return Err(Error::DisallowedEdit {
            variant: ctx.variant_file.to_string(),
            item: transplant.donor.clone(),
            reason: format!(
                "fragment anchor `{}` lies below its `to` anchor `{}`",
                transplant.from, transplant.to
            ),
        });
    }
    let needs_substitution = !transplant.rename.is_empty() || !transplant.literals.is_empty();
    let mut fragment = Vec::new();
    let mut balance = 0;
    let mut statements = 0;
    for line_no in from..=to {
        if let Some(text) = ctx.seed_lines.get(to_usize(line_no).saturating_sub(1)) {
            balance += brace_balance(text);
            let text = if needs_substitution {
                substitute(text, &transplant.rename, &transplant.literals)
            } else {
                (*text).to_string()
            };
            statements += u32::from(is_statement(text.trim()));
            fragment.push(text);
        }
    }
    if balance != 0 {
        return Err(Error::DisallowedEdit {
            variant: ctx.variant_file.to_string(),
            item: transplant.donor.clone(),
            reason: format!(
                "fragment `{}` .. `{}` is not brace-balanced",
                transplant.from, transplant.to
            ),
        });
    }
    let index = find_anchor(lines, &transplant.after, ctx.variant_file, host_key)?;
    let id = pending.next_transplant;
    pending.next_transplant += 1;
    for (offset, text) in fragment.into_iter().enumerate() {
        lines.insert(
            index + 1 + offset,
            Line {
                text,
                seed_line: None,
                transplant: Some(id),
            },
        );
    }
    if transplant.labelled {
        pending.pairs.push(PendingPair {
            variant_file: ctx.variant_file.to_string(),
            clone_type: transplant.clone_type.unwrap_or(ctx.default_type),
            item_key: transplant.donor.clone(),
            seed_start: from,
            seed_end: to,
            transplant: Some(id),
        });
    }
    if let Some(reason) = &transplant.non_clone {
        pending.non_clones.push(PendingNonClone {
            variant_file: ctx.variant_file.to_string(),
            donor_key: transplant.donor.clone(),
            reason: reason.clone(),
            seed_start: from,
            seed_end: to,
            transplant: id,
        });
    }
    Ok(statements)
}

/// Resolve an anchor against a donor item's seed lines, returning the
/// matching absolute seed line (1-based). Like edit anchors, the anchor is
/// compared against each line's whitespace-trimmed text and must match
/// exactly one line of the item.
fn find_seed_anchor(ctx: &RenderContext<'_>, donor: &Item, anchor: &str) -> Result<u32, Error> {
    let mut found = None;
    for line_no in donor.start_line..=donor.end_line {
        let Some(text) = ctx.seed_lines.get(to_usize(line_no).saturating_sub(1)) else {
            continue;
        };
        if text.trim() == anchor {
            if found.is_some() {
                return Err(Error::AmbiguousAnchor {
                    variant: ctx.variant_file.to_string(),
                    item: donor.key.clone(),
                    anchor: anchor.to_string(),
                });
            }
            found = Some(line_no);
        }
    }
    found.ok_or_else(|| Error::AnchorNotFound {
        variant: ctx.variant_file.to_string(),
        item: donor.key.clone(),
        anchor: anchor.to_string(),
    })
}

/// Apply one edit, returning the number of statement lines it inserted or
/// deleted.
fn apply_edit(
    lines: &mut Vec<Line>,
    edit: &EditOp,
    variant: &str,
    item: &str,
) -> Result<u32, Error> {
    let inserted = |text: String| Line {
        text,
        seed_line: None,
        transplant: None,
    };
    match edit {
        EditOp::CommentBefore { text } => {
            lines.insert(0, inserted(format!("// {text}")));
            Ok(0)
        }
        EditOp::CommentAfter { anchor, text } => {
            let index = find_anchor(lines, anchor, variant, item)?;
            let indent = leading_whitespace(&lines[index].text).to_string();
            lines.insert(index + 1, inserted(format!("{indent}// {text}")));
            Ok(0)
        }
        EditOp::BlankAfter { anchor } => {
            let index = find_anchor(lines, anchor, variant, item)?;
            lines.insert(index + 1, inserted(String::new()));
            Ok(0)
        }
        EditOp::RemoveBlankAfter { anchor } => {
            let index = find_anchor(lines, anchor, variant, item)?;
            if lines
                .get(index + 1)
                .is_some_and(|line| line.text.trim().is_empty())
            {
                lines.remove(index + 1);
                Ok(0)
            } else {
                Err(Error::DisallowedEdit {
                    variant: variant.to_string(),
                    item: item.to_string(),
                    reason: format!("no blank line follows anchor `{anchor}`"),
                })
            }
        }
        EditOp::Reindent { unit } => {
            reindent(lines, *unit, variant, item)?;
            Ok(0)
        }
        EditOp::InsertAfter { anchor, lines: new } => {
            let index = find_anchor(lines, anchor, variant, item)?;
            Ok(insert_lines(lines, index + 1, new))
        }
        EditOp::InsertBefore { anchor, lines: new } => {
            let index = find_anchor(lines, anchor, variant, item)?;
            Ok(insert_lines(lines, index, new))
        }
        EditOp::Delete { anchor } => {
            let index = find_anchor(lines, anchor, variant, item)?;
            let removed = lines.remove(index);
            Ok(u32::from(is_statement(removed.text.trim())))
        }
    }
}

fn insert_lines(lines: &mut Vec<Line>, at: usize, new: &[String]) -> u32 {
    let mut statements = 0;
    for (offset, text) in new.iter().enumerate() {
        statements += u32::from(is_statement(text.trim()));
        lines.insert(
            at + offset,
            Line {
                text: text.clone(),
                seed_line: None,
                transplant: None,
            },
        );
    }
    statements
}

fn find_anchor(lines: &[Line], anchor: &str, variant: &str, item: &str) -> Result<usize, Error> {
    let mut found = None;
    for (index, line) in lines.iter().enumerate() {
        if line.text.trim() == anchor {
            if found.is_some() {
                return Err(Error::AmbiguousAnchor {
                    variant: variant.to_string(),
                    item: item.to_string(),
                    anchor: anchor.to_string(),
                });
            }
            found = Some(index);
        }
    }
    found.ok_or_else(|| Error::AnchorNotFound {
        variant: variant.to_string(),
        item: item.to_string(),
        anchor: anchor.to_string(),
    })
}

fn leading_whitespace(text: &str) -> &str {
    &text[..text.len() - text.trim_start().len()]
}

fn reindent(lines: &mut [Line], unit: u8, variant: &str, item: &str) -> Result<(), Error> {
    for line in lines.iter_mut() {
        let trimmed = line.text.trim_start();
        if trimmed.is_empty() {
            continue;
        }
        let indent = leading_whitespace(&line.text);
        if indent.chars().any(|c| c != ' ') || indent.len() % 4 != 0 {
            return Err(Error::DisallowedEdit {
                variant: variant.to_string(),
                item: item.to_string(),
                reason: format!(
                    "cannot reindent `{trimmed}`: indentation is not a multiple of 4 spaces"
                ),
            });
        }
        let new_indent = " ".repeat((indent.len() / 4) * usize::from(unit));
        line.text = format!("{new_indent}{trimmed}");
    }
    Ok(())
}

/// Statement lines of a seed item, excluding the header line.
fn count_statements(seed_lines: &[&str], item: &Item) -> u32 {
    let mut count = 0;
    for line_no in item.start_line.saturating_add(1)..=item.end_line {
        if let Some(text) = seed_lines.get(to_usize(line_no).saturating_sub(1)) {
            count += u32::from(is_statement(text.trim()));
        }
    }
    count
}

/// Output-line span (1-based, inclusive) of all lines whose provenance falls
/// inside the given seed range.
fn mapped_range(lines: &[Line], seed_start: u32, seed_end: u32) -> Option<(u32, u32)> {
    let mut first = None;
    let mut last = None;
    for (index, line) in lines.iter().enumerate() {
        if let Some(seed) = line.seed_line {
            if seed >= seed_start && seed <= seed_end {
                let line_no = to_u32(index + 1);
                if first.is_none() {
                    first = Some(line_no);
                }
                last = Some(line_no);
            }
        }
    }
    first.zip(last)
}

/// Output-line span (1-based, inclusive) of the surviving lines a transplant
/// inserted.
fn transplant_range(lines: &[Line], id: usize) -> Option<(u32, u32)> {
    let mut first = None;
    let mut last = None;
    for (index, line) in lines.iter().enumerate() {
        if line.transplant == Some(id) {
            let line_no = to_u32(index + 1);
            if first.is_none() {
                first = Some(line_no);
            }
            last = Some(line_no);
        }
    }
    first.zip(last)
}

fn resolve_pairs(
    pending: &[PendingPair],
    rendered: &[RenderedVariant],
    seed_file: &str,
) -> Result<Vec<LabelPair>, Error> {
    pending
        .iter()
        .enumerate()
        .map(|(index, pair)| {
            let variant = rendered
                .iter()
                .find(|rendered| rendered.file == pair.variant_file)
                .ok_or_else(|| Error::UnknownNonCloneRef {
                    reference: pair.variant_file.clone(),
                })?;
            let (start, end) = pair
                .transplant
                .map_or_else(
                    || mapped_range(&variant.lines, pair.seed_start, pair.seed_end),
                    |id| transplant_range(&variant.lines, id),
                )
                .ok_or_else(|| Error::EmptyRange {
                    variant: pair.variant_file.clone(),
                    item: pair.item_key.clone(),
                })?;
            Ok(LabelPair {
                id: format!("cp-{:03}", index + 1),
                clone_type: pair.clone_type,
                fragments: vec![
                    Fragment {
                        file: seed_file.to_string(),
                        start_line: pair.seed_start,
                        end_line: pair.seed_end,
                    },
                    Fragment {
                        file: pair.variant_file.clone(),
                        start_line: start,
                        end_line: end,
                    },
                ],
            })
        })
        .collect()
}

fn resolve_non_clones(
    specs: &[NonCloneSpec],
    by_key: &BTreeMap<&str, &Item>,
    rendered: &[RenderedVariant],
    seed_file: &str,
) -> Result<Vec<NonClone>, Error> {
    specs
        .iter()
        .enumerate()
        .map(|(index, spec)| {
            let function = by_key.get(spec.function.as_str()).copied().ok_or_else(|| {
                Error::UnknownNonCloneRef {
                    reference: spec.function.clone(),
                }
            })?;
            let variant = rendered
                .iter()
                .find(|rendered| rendered.file == spec.variant)
                .ok_or_else(|| Error::UnknownNonCloneRef {
                    reference: spec.variant.clone(),
                })?;
            let (start, end) = mapped_range(&variant.lines, function.start_line, function.end_line)
                .ok_or_else(|| Error::EmptyRange {
                    variant: spec.variant.clone(),
                    item: spec.function.clone(),
                })?;
            Ok(NonClone {
                id: format!("nc-{:03}", index + 1),
                reason: spec.reason.clone(),
                fragments: vec![
                    Fragment {
                        file: seed_file.to_string(),
                        start_line: function.start_line,
                        end_line: function.end_line,
                    },
                    Fragment {
                        file: spec.variant.clone(),
                        start_line: start,
                        end_line: end,
                    },
                ],
            })
        })
        .collect()
}

/// Resolve the transplant-derived non-clones. Their ids continue the
/// numbering after the spec-level non-clones (`id_offset` entries).
fn resolve_transplant_non_clones(
    pending: &[PendingNonClone],
    rendered: &[RenderedVariant],
    seed_file: &str,
    id_offset: usize,
) -> Result<Vec<NonClone>, Error> {
    pending
        .iter()
        .enumerate()
        .map(|(index, entry)| {
            let variant = rendered
                .iter()
                .find(|rendered| rendered.file == entry.variant_file)
                .ok_or_else(|| Error::UnknownNonCloneRef {
                    reference: entry.variant_file.clone(),
                })?;
            let (start, end) =
                transplant_range(&variant.lines, entry.transplant).ok_or_else(|| {
                    Error::EmptyRange {
                        variant: entry.variant_file.clone(),
                        item: entry.donor_key.clone(),
                    }
                })?;
            Ok(NonClone {
                id: format!("nc-{:03}", id_offset + index + 1),
                reason: entry.reason.clone(),
                fragments: vec![
                    Fragment {
                        file: seed_file.to_string(),
                        start_line: entry.seed_start,
                        end_line: entry.seed_end,
                    },
                    Fragment {
                        file: entry.variant_file.clone(),
                        start_line: start,
                        end_line: end,
                    },
                ],
            })
        })
        .collect()
}

fn collect_files(
    rendered: Vec<RenderedVariant>,
    labels: &LabelSet,
) -> Result<BTreeMap<String, String>, Error> {
    let mut files = BTreeMap::new();
    for variant in rendered {
        let mut text = variant
            .lines
            .iter()
            .map(|line| line.text.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        text.push('\n');
        if files.insert(variant.file.clone(), text).is_some() {
            return Err(Error::DuplicateFile { file: variant.file });
        }
    }
    let labels_json = serde_json::to_string_pretty(labels).map_err(Error::Serialize)?;
    if files
        .insert(LABELS_FILE.to_string(), format!("{labels_json}\n"))
        .is_some()
    {
        return Err(Error::DuplicateFile {
            file: LABELS_FILE.to_string(),
        });
    }
    Ok(files)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    const SEED: &str = "\
// seed

fn add(a: i32, b: i32) -> i32 {
    let sum = a + b;
    sum
}

fn twice(x: i32) -> i32 {
    let y = x * 2;
    y
}
";

    fn base_spec() -> MutationSpec {
        MutationSpec {
            schema_version: 0,
            language: "rust".to_string(),
            seed: "seed.rs".to_string(),
            variants: Vec::new(),
            non_clones: Vec::new(),
        }
    }

    fn item(key: &str) -> ItemSpec {
        ItemSpec {
            item: key.to_string(),
            labelled: true,
            clone_type: None,
            rename: BTreeMap::new(),
            literals: BTreeMap::new(),
            transplants: Vec::new(),
            edits: Vec::new(),
            target_change_rate: None,
        }
    }

    fn transplant(donor: &str, from: &str, to: &str, after: &str) -> TransplantSpec {
        TransplantSpec {
            donor: donor.to_string(),
            from: from.to_string(),
            to: to.to_string(),
            after: after.to_string(),
            labelled: false,
            clone_type: None,
            rename: BTreeMap::new(),
            literals: BTreeMap::new(),
            non_clone: None,
        }
    }

    fn map(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|&(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    fn type2_spec() -> MutationSpec {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v2.rs".to_string(),
            clone_type: CloneType::Type2,
            header_comment: "Type-2 variant.".to_string(),
            items: vec![ItemSpec {
                rename: map(&[("a", "p"), ("b", "q"), ("sum", "total")]),
                ..item("fn add")
            }],
        });
        spec
    }

    #[test]
    fn generate_is_deterministic() {
        let first = generate(&type2_spec(), SEED).expect("first run");
        let second = generate(&type2_spec(), SEED).expect("second run");
        assert_eq!(first, second);
    }

    #[test]
    fn type2_variant_renames_whole_tokens_and_preserves_structure() {
        let corpus = generate(&type2_spec(), SEED).expect("generates");
        let expected = format!(
            "// Type-2 variant.\n{GENERATED_MARKER}\n\n\
             fn add(p: i32, q: i32) -> i32 {{\n    let total = p + q;\n    total\n}}\n"
        );
        assert_eq!(corpus.files["v2.rs"], expected);
    }

    #[test]
    fn label_ranges_are_computed_from_the_actual_edits() {
        let corpus = generate(&type2_spec(), SEED).expect("generates");
        assert_eq!(corpus.labels.clone_pairs.len(), 1);
        let pair = &corpus.labels.clone_pairs[0];
        assert_eq!(pair.id, "cp-001");
        assert_eq!(pair.clone_type, CloneType::Type2);
        // Seed: `fn add` spans lines 3..=6. Variant: header comment, marker
        // and one blank line precede it, so it spans lines 4..=7.
        assert_eq!(
            pair.fragments,
            vec![
                Fragment {
                    file: "seed.rs".to_string(),
                    start_line: 3,
                    end_line: 6,
                },
                Fragment {
                    file: "v2.rs".to_string(),
                    start_line: 4,
                    end_line: 7,
                },
            ]
        );
    }

    #[test]
    fn type1_comment_before_stays_outside_the_labelled_range() {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v1.rs".to_string(),
            clone_type: CloneType::Type1,
            header_comment: "Type-1 variant.".to_string(),
            items: vec![ItemSpec {
                edits: vec![
                    EditOp::CommentBefore {
                        text: "Adds two numbers.".to_string(),
                    },
                    EditOp::BlankAfter {
                        anchor: "let sum = a + b;".to_string(),
                    },
                ],
                ..item("fn add")
            }],
        });
        let corpus = generate(&spec, SEED).expect("generates");
        let pair = &corpus.labels.clone_pairs[0];
        // Line 4 is the inserted comment; the fragment starts at the `fn`
        // header on line 5 and the inserted blank line stays inside the span.
        assert_eq!(pair.fragments[1].start_line, 5);
        assert_eq!(pair.fragments[1].end_line, 9);
    }

    #[test]
    fn type3_records_the_achieved_change_rate() {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v3.rs".to_string(),
            clone_type: CloneType::Type3,
            header_comment: "Type-3 variant.".to_string(),
            items: vec![ItemSpec {
                target_change_rate: Some(0.5),
                edits: vec![EditOp::InsertAfter {
                    anchor: "let sum = a + b;".to_string(),
                    lines: vec!["    let extra = 0;".to_string()],
                }],
                ..item("fn add")
            }],
        });
        let corpus = generate(&spec, SEED).expect("generates");
        assert_eq!(corpus.change_rates.len(), 1);
        let rate = &corpus.change_rates[0];
        // `fn add` has two statement lines; one statement was inserted.
        assert_eq!(rate.changed_statements, 1);
        assert_eq!(rate.total_statements, 2);
        assert!((rate.achieved() - 0.5).abs() < 1e-9);
        // The inserted statement extends the variant fragment by one line.
        let pair = &corpus.labels.clone_pairs[0];
        assert_eq!(pair.fragments[1].start_line, 4);
        assert_eq!(pair.fragments[1].end_line, 8);
    }

    #[test]
    fn delete_shrinks_the_range_and_counts_as_change() {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v3.rs".to_string(),
            clone_type: CloneType::Type3,
            header_comment: "Type-3 variant.".to_string(),
            items: vec![ItemSpec {
                edits: vec![EditOp::Delete {
                    anchor: "let y = x * 2;".to_string(),
                }],
                ..item("fn twice")
            }],
        });
        let corpus = generate(&spec, SEED).expect("generates");
        assert_eq!(corpus.change_rates[0].changed_statements, 1);
        let pair = &corpus.labels.clone_pairs[0];
        assert_eq!(pair.fragments[1].start_line, 4);
        assert_eq!(pair.fragments[1].end_line, 6);
    }

    #[test]
    fn non_clone_ranges_are_recomputed() {
        let mut spec = type2_spec();
        spec.non_clones.push(NonCloneSpec {
            reason: "helper-boilerplate".to_string(),
            function: "fn add".to_string(),
            variant: "v2.rs".to_string(),
        });
        let corpus = generate(&spec, SEED).expect("generates");
        assert_eq!(corpus.labels.non_clones.len(), 1);
        let non_clone = &corpus.labels.non_clones[0];
        assert_eq!(non_clone.id, "nc-001");
        assert_eq!(non_clone.fragments[0].start_line, 3);
        assert_eq!(non_clone.fragments[1].start_line, 4);
    }

    #[test]
    fn item_clone_type_override_is_used_in_labels() {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v3.rs".to_string(),
            clone_type: CloneType::Type3,
            header_comment: "Type-3 variant.".to_string(),
            items: vec![
                ItemSpec {
                    edits: vec![EditOp::Delete {
                        anchor: "let sum = a + b;".to_string(),
                    }],
                    ..item("fn add")
                },
                ItemSpec {
                    clone_type: Some(CloneType::Type1),
                    ..item("fn twice")
                },
            ],
        });
        let corpus = generate(&spec, SEED).expect("generates");
        assert_eq!(corpus.labels.clone_pairs[0].clone_type, CloneType::Type3);
        assert_eq!(corpus.labels.clone_pairs[1].clone_type, CloneType::Type1);
    }

    #[test]
    fn reindent_changes_indentation_only() {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v1.rs".to_string(),
            clone_type: CloneType::Type1,
            header_comment: "Type-1 variant.".to_string(),
            items: vec![ItemSpec {
                edits: vec![EditOp::Reindent { unit: 2 }],
                ..item("fn add")
            }],
        });
        let corpus = generate(&spec, SEED).expect("generates");
        assert!(corpus.files["v1.rs"].contains("\n  let sum = a + b;\n"));
    }

    /// Seed for the transplant tests. `fn donor` spans lines 3..=9 with the
    /// fragment `let mut total = 0;` .. `total` on lines 4..=8; `fn host`
    /// spans lines 11..=17.
    const PARTIAL_SEED: &str = "\
// seed

fn donor(values: &[i32]) -> i32 {
    let mut total = 0;
    for value in values {
        total += *value;
    }
    total
}

fn host(items: &[i32]) -> i32 {
    let mut count = 0;
    for item in items {
        count += 1;
    }
    count
}
";

    fn partial_spec() -> MutationSpec {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "partial.rs".to_string(),
            clone_type: CloneType::Type3,
            header_comment: "Partial variant.".to_string(),
            items: vec![ItemSpec {
                labelled: false,
                transplants: vec![TransplantSpec {
                    labelled: true,
                    clone_type: Some(CloneType::Type1),
                    ..transplant(
                        "fn donor",
                        "let mut total = 0;",
                        "total",
                        "let mut count = 0;",
                    )
                }],
                ..item("fn host")
            }],
        });
        spec
    }

    #[test]
    fn transplant_inserts_the_donor_fragment_verbatim() {
        let corpus = generate(&partial_spec(), PARTIAL_SEED).expect("generates");
        let expected = format!(
            "// Partial variant.\n{GENERATED_MARKER}\n\n\
             fn host(items: &[i32]) -> i32 {{\n    let mut count = 0;\n    let mut total = 0;\n    for value in values {{\n        total += *value;\n    }}\n    total\n    for item in items {{\n        count += 1;\n    }}\n    count\n}}\n"
        );
        assert_eq!(corpus.files["partial.rs"], expected);
        // The transplanted statements count toward the host's change rate.
        assert_eq!(corpus.change_rates.len(), 1);
        assert_eq!(corpus.change_rates[0].changed_statements, 4);
        assert_eq!(corpus.change_rates[0].total_statements, 4);
    }

    #[test]
    fn transplant_pairs_the_donor_fragment_with_the_transplanted_lines() {
        let corpus = generate(&partial_spec(), PARTIAL_SEED).expect("generates");
        assert_eq!(corpus.labels.clone_pairs.len(), 1);
        let pair = &corpus.labels.clone_pairs[0];
        assert_eq!(pair.clone_type, CloneType::Type1);
        // Donor fragment: seed lines 4..=8. Variant: header, marker, blank
        // line and the host's first two lines precede it, so lines 6..=10.
        assert_eq!(
            pair.fragments,
            vec![
                Fragment {
                    file: "seed.rs".to_string(),
                    start_line: 4,
                    end_line: 8,
                },
                Fragment {
                    file: "partial.rs".to_string(),
                    start_line: 6,
                    end_line: 10,
                },
            ]
        );
    }

    #[test]
    fn renamed_transplant_is_a_type2_partial_clone() {
        let mut spec = partial_spec();
        let transplanted = &mut spec.variants[0].items[0].transplants[0];
        transplanted.clone_type = Some(CloneType::Type2);
        transplanted.rename = map(&[("total", "sum"), ("value", "entry"), ("values", "items")]);
        transplanted.literals = map(&[("0", "1")]);
        let corpus = generate(&spec, PARTIAL_SEED).expect("generates");
        let text = &corpus.files["partial.rs"];
        assert!(text.contains("\n    let mut sum = 1;\n    for entry in items {\n        sum += *entry;\n    }\n    sum\n"));
        let pair = &corpus.labels.clone_pairs[0];
        assert_eq!(pair.clone_type, CloneType::Type2);
        // Substitution preserves line structure, so the ranges are unchanged.
        assert_eq!(pair.fragments[0].start_line, 4);
        assert_eq!(pair.fragments[0].end_line, 8);
        assert_eq!(pair.fragments[1].start_line, 6);
        assert_eq!(pair.fragments[1].end_line, 10);
    }

    #[test]
    fn transplant_non_clone_is_labelled_at_fragment_granularity() {
        let mut spec = partial_spec();
        let transplanted = &mut spec.variants[0].items[0].transplants[0];
        transplanted.labelled = false;
        transplanted.clone_type = None;
        transplanted.non_clone = Some("loop-boilerplate".to_string());
        spec.non_clones.push(NonCloneSpec {
            reason: "host-scaffold".to_string(),
            function: "fn host".to_string(),
            variant: "partial.rs".to_string(),
        });
        let corpus = generate(&spec, PARTIAL_SEED).expect("generates");
        assert!(corpus.labels.clone_pairs.is_empty());
        assert_eq!(corpus.labels.non_clones.len(), 2);
        // Spec-level non-clones come first; the transplant-derived one
        // continues the id numbering at fragment granularity.
        assert_eq!(corpus.labels.non_clones[0].id, "nc-001");
        assert_eq!(corpus.labels.non_clones[0].reason, "host-scaffold");
        let fragment_level = &corpus.labels.non_clones[1];
        assert_eq!(fragment_level.id, "nc-002");
        assert_eq!(fragment_level.reason, "loop-boilerplate");
        assert_eq!(
            fragment_level.fragments,
            vec![
                Fragment {
                    file: "seed.rs".to_string(),
                    start_line: 4,
                    end_line: 8,
                },
                Fragment {
                    file: "partial.rs".to_string(),
                    start_line: 6,
                    end_line: 10,
                },
            ]
        );
    }

    #[test]
    fn transplant_range_survives_a_donor_copy_in_the_same_variant() {
        let mut spec = partial_spec();
        spec.variants[0].items.insert(
            0,
            ItemSpec {
                clone_type: Some(CloneType::Type1),
                ..item("fn donor")
            },
        );
        let corpus = generate(&spec, PARTIAL_SEED).expect("generates");
        assert_eq!(corpus.labels.clone_pairs.len(), 2);
        // The donor's own copy maps by provenance (variant lines 4..=10);
        // the transplant maps by insertion identity, unaffected by the donor
        // copy carrying the same seed lines.
        assert_eq!(corpus.labels.clone_pairs[0].fragments[1].start_line, 4);
        assert_eq!(corpus.labels.clone_pairs[0].fragments[1].end_line, 10);
        assert_eq!(corpus.labels.clone_pairs[1].fragments[0].start_line, 4);
        assert_eq!(corpus.labels.clone_pairs[1].fragments[0].end_line, 8);
        assert_eq!(corpus.labels.clone_pairs[1].fragments[1].start_line, 14);
        assert_eq!(corpus.labels.clone_pairs[1].fragments[1].end_line, 18);
    }

    #[test]
    fn transplant_generation_is_deterministic() {
        let first = generate(&partial_spec(), PARTIAL_SEED).expect("first run");
        let second = generate(&partial_spec(), PARTIAL_SEED).expect("second run");
        assert_eq!(first, second);
    }

    #[test]
    fn transplant_requires_a_type3_host() {
        let mut spec = partial_spec();
        spec.variants[0].clone_type = CloneType::Type2;
        spec.variants[0].items[0].transplants[0].clone_type = Some(CloneType::Type1);
        assert!(matches!(
            generate(&spec, PARTIAL_SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn labelled_transplant_must_declare_type1_or_type2() {
        let mut spec = partial_spec();
        // Without an override the label type defaults to the variant's
        // type-3, which a labelled transplant cannot carry.
        spec.variants[0].items[0].transplants[0].clone_type = None;
        assert!(matches!(
            generate(&spec, PARTIAL_SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn type1_transplant_rejects_substitution() {
        let mut spec = partial_spec();
        spec.variants[0].items[0].transplants[0].rename = map(&[("total", "sum")]);
        assert!(matches!(
            generate(&spec, PARTIAL_SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn transplant_cannot_be_both_labelled_and_non_clone() {
        let mut spec = partial_spec();
        spec.variants[0].items[0].transplants[0].non_clone = Some("boilerplate".to_string());
        assert!(matches!(
            generate(&spec, PARTIAL_SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn transplant_unknown_donor_is_an_error() {
        let mut spec = partial_spec();
        spec.variants[0].items[0].transplants[0].donor = "fn missing".to_string();
        assert!(matches!(
            generate(&spec, PARTIAL_SEED),
            Err(Error::UnknownItem { .. })
        ));
    }

    #[test]
    fn unbalanced_transplant_fragment_is_rejected() {
        let mut spec = partial_spec();
        spec.variants[0].items[0].transplants[0] = TransplantSpec {
            labelled: true,
            clone_type: Some(CloneType::Type1),
            ..transplant(
                "fn donor",
                "for value in values {",
                "total += *value;",
                "let mut count = 0;",
            )
        };
        assert!(matches!(
            generate(&spec, PARTIAL_SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn reversed_transplant_anchors_are_rejected() {
        let mut spec = partial_spec();
        spec.variants[0].items[0].transplants[0] = TransplantSpec {
            labelled: true,
            clone_type: Some(CloneType::Type1),
            ..transplant(
                "fn donor",
                "total",
                "let mut total = 0;",
                "let mut count = 0;",
            )
        };
        assert!(matches!(
            generate(&spec, PARTIAL_SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn unknown_item_is_an_error() {
        let mut spec = type2_spec();
        spec.variants[0].items[0].item = "fn missing".to_string();
        assert!(matches!(
            generate(&spec, SEED),
            Err(Error::UnknownItem { .. })
        ));
    }

    #[test]
    fn ambiguous_anchor_is_an_error() {
        let seed = "fn f() {\n    same();\n    same();\n}\n";
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v3.rs".to_string(),
            clone_type: CloneType::Type3,
            header_comment: "Variant.".to_string(),
            items: vec![ItemSpec {
                edits: vec![EditOp::Delete {
                    anchor: "same();".to_string(),
                }],
                ..item("fn f")
            }],
        });
        assert!(matches!(
            generate(&spec, seed),
            Err(Error::AmbiguousAnchor { .. })
        ));
    }

    #[test]
    fn missing_anchor_is_an_error() {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v3.rs".to_string(),
            clone_type: CloneType::Type3,
            header_comment: "Variant.".to_string(),
            items: vec![ItemSpec {
                edits: vec![EditOp::Delete {
                    anchor: "nowhere();".to_string(),
                }],
                ..item("fn add")
            }],
        });
        assert!(matches!(
            generate(&spec, SEED),
            Err(Error::AnchorNotFound { .. })
        ));
    }

    #[test]
    fn type1_rejects_substitution() {
        let mut spec = base_spec();
        spec.variants.push(VariantSpec {
            file: "v1.rs".to_string(),
            clone_type: CloneType::Type1,
            header_comment: "Variant.".to_string(),
            items: vec![ItemSpec {
                rename: map(&[("a", "b")]),
                ..item("fn add")
            }],
        });
        assert!(matches!(
            generate(&spec, SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn type2_rejects_statement_edits() {
        let mut spec = type2_spec();
        spec.variants[0].items[0].edits.push(EditOp::Delete {
            anchor: "sum".to_string(),
        });
        assert!(matches!(
            generate(&spec, SEED),
            Err(Error::DisallowedEdit { .. })
        ));
    }

    #[test]
    fn unknown_language_is_rejected() {
        let mut spec = type2_spec();
        spec.language = "fortran".to_string();
        assert!(matches!(
            generate(&spec, SEED),
            Err(Error::UnsupportedLanguage { .. })
        ));
    }

    #[test]
    fn c_seed_items_are_mutated_like_rust_ones() {
        let seed = "\
int add(int a, int b) {
    int sum = a + b;
    return sum;
}
";
        let mut spec = base_spec();
        spec.language = "c".to_string();
        spec.seed = "seed.c".to_string();
        spec.variants.push(VariantSpec {
            file: "v2.c".to_string(),
            clone_type: CloneType::Type2,
            header_comment: "Type-2 variant.".to_string(),
            items: vec![ItemSpec {
                rename: map(&[("a", "p"), ("b", "q"), ("sum", "total")]),
                ..item("fn add")
            }],
        });
        let corpus = generate(&spec, seed).expect("generates");
        let expected = format!(
            "// Type-2 variant.\n{GENERATED_MARKER}\n\n\
             int add(int p, int q) {{\n    int total = p + q;\n    return total;\n}}\n"
        );
        assert_eq!(corpus.files["v2.c"], expected);
        assert_eq!(corpus.labels.language, "c");
    }

    #[test]
    fn wrong_schema_version_is_rejected() {
        let mut spec = type2_spec();
        spec.schema_version = 99;
        assert!(matches!(
            generate(&spec, SEED),
            Err(Error::UnsupportedSchemaVersion(99))
        ));
    }

    #[test]
    fn labels_file_round_trips_through_the_eval_parser() {
        let corpus = generate(&type2_spec(), SEED).expect("generates");
        let parsed = LabelSet::from_json(&corpus.files[LABELS_FILE]).expect("labels parse");
        assert_eq!(parsed, corpus.labels);
    }

    #[test]
    fn first_difference_reports_the_first_diverging_line() {
        assert_eq!(first_difference("a\nb\n", "a\nb\n"), None);
        assert_eq!(first_difference("a\nb\n", "a\nc\n"), Some(2));
        assert_eq!(first_difference("a\n", "a\nb\n"), Some(2));
    }
}
