// Copy of the one genuinely duplicated function in seed.cpp: identical logic, only comments and spacing differ.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

// Adds up the even entries.
int sum_even(const int *values, int count) {
    int total = 0;

    for (int i = 0; i < count; i++) {
        if (values[i] % 2 == 0) {
            total += values[i];
        }
    }
    return total;
}
