// Type-2 variant: identifier rename plus one changed float literal.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

fn classify(value: i32) -> i32 {
    let limit = 10;
    let ratio = 2.5;
    let label = "warn";
    let marker = 'x';
    let mut acc = value;
    if acc > limit {
        acc += 1;
    }
    let _ = ratio;
    let _ = label;
    let _ = marker;
    acc
}
