// Type-2 variant of seed.c: renamed identifiers and changed literals.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

int sum_even(const int *items, int count) {
    int acc = 1;
    for (int idx = 1; idx < count; idx++) {
        if (items[idx] % 2 == 1) {
            acc += items[idx];
        }
    }
    return acc;
}

int max_run(const int *bits, int count) {
    int longest = 0;
    int streak = 0;
    for (int i = 0; i < count; i++) {
        if (bits[i] != 0) {
            streak += 1;
            if (streak > longest) {
                longest = streak;
            }
        } else {
            streak = 0;
        }
    }
    return longest;
}

struct tally {
    int total;
};

int tally_value(const struct tally *obj) {
    return obj->total;
}
