// Type-1 variant of seed.c: identical logic, only comments and spacing differ.
// Generated by codehelion-corpus-gen; edit the mutation spec instead.

// Adds up the even entries.
int sum_even(const int *values, int count) {
    int total = 0;

    for (int i = 0; i < count; i++) {
        if (values[i] % 2 == 0) {
            total += values[i];
        }
    }
    return total;
}

// Longest run of nonzero flags.
int max_run(const int *flags, int count) {
    int best = 0;
    int current = 0;
    for (int i = 0; i < count; i++) {
        if (flags[i] != 0) {
            current += 1;
            if (current > best) {
                best = current;
            }
        } else {
            current = 0;
            // A zero flag resets the run.
        }
    }
    return best;
}
