//! Attribute and derive macros are invocations too, and each one the helper
//! does not expand is recorded once, for the reason that holds for it.

use super::*;

const SOURCE: &str = r"use macros::{traced, Tagged};

#[traced]
pub fn instrumented() {}

#[macros::traced]
pub fn by_path() {}

#[derive(Tagged)]
pub struct Derived;

#[derive(Debug)]
pub struct Builtin;

#[cfg_attr(all(), derive(Tagged))]
pub struct Conditional;

#[derive(Absent)]
pub struct MissingDerive;

#[missing::attribute]
pub fn missing_attribute() {}

#[inline]
#[allow(dead_code)]
pub fn not_macros() {}
";

const MACROS: &str = r"use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn traced(_arguments: TokenStream, item: TokenStream) -> TokenStream {
    item
}

#[proc_macro_derive(Tagged)]
pub fn tagged(_item: TokenStream) -> TokenStream {
    TokenStream::new()
}
";

fn workspace() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("a scratch directory");
    let root = directory.path();
    for (path, text) in [
        (
            "Cargo.toml",
            "[workspace]\nmembers = [\"app\", \"macros\"]\nresolver = \"2\"\n",
        ),
        (
            "Cargo.lock",
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\ndependencies = [\n \"macros\",\n]\n\n[[package]]\nname = \"macros\"\nversion = \"0.1.0\"\n",
        ),
        (
            "app/Cargo.toml",
            "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\npublish = false\n\n[dependencies]\nmacros = { path = \"../macros\" }\n",
        ),
        ("app/src/lib.rs", SOURCE),
        (
            "macros/Cargo.toml",
            "[package]\nname = \"macros\"\nversion = \"0.1.0\"\nedition = \"2021\"\npublish = false\n\n[lib]\nproc-macro = true\n",
        ),
        ("macros/src/lib.rs", MACROS),
    ] {
        let path = root.join(path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, text).unwrap();
    }
    directory
}

/// What each recorded invocation says, keyed by the text it covers.
fn recorded(ir: &CompilerIr) -> Vec<(String, &'static str)> {
    ir.unexpanded_macros
        .iter()
        .map(|macro_| {
            let start = usize::try_from(macro_.invocation.start_byte).unwrap();
            let end = usize::try_from(macro_.invocation.end_byte).unwrap();
            (SOURCE[start..end].to_owned(), macro_.reason.name())
        })
        .collect()
}

#[test]
fn every_attribute_and_derive_invocation_is_recorded_once_with_its_own_reason() {
    let workspace = workspace();
    let unit = UnitRef {
        unit: "app".to_string(),
        file: workspace
            .path()
            .join("app/src/lib.rs")
            .display()
            .to_string(),
        variant: "host".to_string(),
    };
    let Analysis::Done(ir) = helper()
        .analyze(&unit, &Capability::ALL)
        .expect("the helper should answer")
    else {
        panic!("the workspace was declined");
    };

    let mut found = recorded(&ir);
    found.sort();
    let mut expected = vec![
        (
            "#[traced]".to_owned(),
            UnexpandedMacroReason::RequiresExecution.name(),
        ),
        (
            "#[macros::traced]".to_owned(),
            UnexpandedMacroReason::RequiresExecution.name(),
        ),
        (
            "#[derive(Tagged)]".to_owned(),
            UnexpandedMacroReason::RequiresExecution.name(),
        ),
        (
            "#[derive(Debug)]".to_owned(),
            UnexpandedMacroReason::ExpansionUnavailable.name(),
        ),
        (
            "derive(Tagged)".to_owned(),
            UnexpandedMacroReason::RequiresExecution.name(),
        ),
        (
            "#[derive(Absent)]".to_owned(),
            UnexpandedMacroReason::Unresolved.name(),
        ),
        (
            "#[missing::attribute]".to_owned(),
            UnexpandedMacroReason::Unresolved.name(),
        ),
    ];
    expected.sort();
    assert_eq!(found, expected, "{:#?}", ir.unexpanded_macros);
}
