//! What a tree's own Cargo configuration is allowed to decide.
//!
//! Cargo finds `.cargo/config.toml` by walking up from the directory it was
//! started in, and reading a workspace means starting Cargo inside it. The keys
//! there name programs to run — a compiler, or a wrapper around one — so a tree
//! that names one is naming a program to be run as whoever started the scan.
//! Everything here is driven through the real program against a real tree with
//! a real script in it, because a marker file appearing is the only evidence
//! that settles whether something ran.

use super::*;

/// A project that asks Cargo to run a program.
struct TreeNamingAProgram {
    /// Held so the tree outlives the test that reads it.
    _directory: tempfile::TempDir,
    root: PathBuf,
    source: PathBuf,
}

impl TreeNamingAProgram {
    fn unit(&self) -> UnitRef {
        UnitRef {
            unit: "names_a_program".to_owned(),
            file: self.source.display().to_string(),
            variant: "host".to_owned(),
        }
    }
}

/// A project whose `.cargo/config.toml` sets `build.rustc-wrapper` to `wrapper`.
fn tree_naming(wrapper: &Path) -> TreeNamingAProgram {
    let directory = tempfile::tempdir().expect("a temporary directory");
    let root = directory.path().join("project");
    let source = root.join("src/lib.rs");
    std::fs::create_dir_all(root.join("src")).expect("create the source directory");
    std::fs::create_dir_all(root.join(".cargo")).expect("create the configuration directory");
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"names-a-program\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n",
    )
    .expect("write the manifest");
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"names-a-program\"\nversion = \"0.1.0\"\n",
    )
    .expect("write the lockfile");
    std::fs::write(
        root.join(".cargo/config.toml"),
        format!(
            "[build]\nrustc-wrapper = \"{}\"\n",
            wrapper.display().to_string().replace('\\', "\\\\")
        ),
    )
    .expect("write the Cargo configuration");
    std::fs::write(&source, "pub fn answer() -> u8 { 42 }\n").expect("write the source");

    TreeNamingAProgram {
        _directory: directory,
        root,
        source,
    }
}

/// A script that records having been started and then runs the compiler it was
/// handed, which is what a wrapper is.
#[cfg(unix)]
fn wrapper_touching(marker: &Path, at: &Path) -> PathBuf {
    use std::os::unix::fs::PermissionsExt;

    let script = at.join("wrapper.sh");
    std::fs::write(
        &script,
        format!("#!/bin/sh\n: > \"{}\"\nexec \"$@\"\n", marker.display()),
    )
    .expect("write the wrapper script");
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755))
        .expect("make the wrapper startable");
    script
}

/// The same project, carrying a build script.
///
/// Only the tree whose test permits running build scripts gets one, and it gets
/// one because the permission has to have something to buy: without a build
/// script, whether the named wrapper is reached at all depends on whether the
/// workspace load also compiles the library, which is the project-model crate's
/// decision rather than the permission's. Every other tree here stays without
/// one, since a declared build script is refused on its own account and would
/// stand in for the key each of those tests is about.
fn tree_building_a_script(wrapper: &Path) -> TreeNamingAProgram {
    let tree = tree_naming(wrapper);
    std::fs::write(tree.root.join("build.rs"), "fn main() {}\n").expect("write the build script");
    tree
}

/// The same project, carrying a configuration that starts nothing.
fn tree_starting_nothing() -> TreeNamingAProgram {
    let tree = tree_naming(Path::new("/nowhere/at/all/wrapper"));
    std::fs::write(
        tree.root.join(".cargo/config.toml"),
        "[net]\noffline = true\n\n[term]\nverbose = false\n",
    )
    .expect("rewrite the Cargo configuration");
    tree
}

/// A program that starts the helper with `wrapper` named in its environment,
/// which is how a helper inherits one: a test cannot set its own environment
/// without setting it for every test running beside it.
#[cfg(unix)]
fn helper_inheriting(wrapper: &Path, at: &Path) -> PathBuf {
    use std::os::unix::fs::PermissionsExt;

    let script = at.join("start-helper.sh");
    std::fs::write(
        &script,
        format!(
            "#!/bin/sh\nRUSTC_WRAPPER=\"{}\" exec \"{}\"\n",
            wrapper.display(),
            env!("CARGO_BIN_EXE_codehelion-backend-rust")
        ),
    )
    .expect("write the starting script");
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755))
        .expect("make the starting script startable");
    script
}

/// Start the helper through a script this process wrote a moment ago.
///
/// A script is refused for as long as anything still holds it open for writing,
/// and a process spawned by a test running beside this one inherits every
/// descriptor open at the instant it forks — including this one, until the
/// child reaches its own program. The file is closed before it is named here,
/// so the refusal describes the machine rather than the script, and the only
/// thing to do with it is let it pass.
#[cfg(unix)]
fn start_through(script: &Path) -> Helper {
    use codehelion_helper::{HelperError, SandboxError};

    fn still_being_written(error: &HelperError) -> bool {
        matches!(
            error,
            HelperError::Sandbox(SandboxError::NotStarted { source, .. })
                if source.kind() == std::io::ErrorKind::ExecutableFileBusy
        )
    }

    let deadline = std::time::Instant::now() + Duration::from_secs(30);
    let mut started = Helper::start(script, PATIENT);
    while matches!(&started, Err(error) if still_being_written(error))
        && std::time::Instant::now() < deadline
    {
        std::thread::sleep(Duration::from_millis(50));
        started = Helper::start(script, PATIENT);
    }
    started.expect("the helper should start and shake hands")
}

/// A program that starts the helper with no wrapper named in its environment.
///
/// The mirror of [`helper_inheriting`], and needed for the same reason: an
/// environment variable outranks the file for these keys, so a suite run under
/// a tool that names its own wrapper — a coverage run names one — would be
/// asking whether the tree's choice wins against a choice already made. What
/// the tree decides can only be read where nothing else has decided it.
#[cfg(unix)]
fn helper_choosing_nothing(at: &Path) -> PathBuf {
    use std::os::unix::fs::PermissionsExt;

    let script = at.join("start-helper-plain.sh");
    std::fs::write(
        &script,
        format!(
            "#!/bin/sh\nunset RUSTC_WRAPPER RUSTC_WORKSPACE_WRAPPER CARGO_BUILD_RUSTC_WRAPPER CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER\nexec \"{}\"\n",
            env!("CARGO_BIN_EXE_codehelion-backend-rust")
        ),
    )
    .expect("write the starting script");
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755))
        .expect("make the starting script startable");
    script
}

/// The tree names a program, nothing permitted running one, so nothing runs it
/// — not while the build is described, which happens before any permission has
/// been asked for, and not while a unit is analysed.
#[test]
#[cfg(unix)]
fn a_tree_that_names_a_wrapper_does_not_get_it_run() {
    let holder = tempfile::tempdir().expect("a temporary directory");
    let marker = holder.path().join("marker");
    let wrapper = wrapper_touching(&marker, holder.path());
    let tree = tree_naming(&wrapper);

    let mut helper = helper();
    let described = helper.describe(&tree.root);
    assert!(
        !marker.exists(),
        "{} appeared while the build was being described: the tree chose the program that ran",
        marker.display()
    );
    let answer = helper
        .analyze(&tree.unit(), &[Capability::Types])
        .expect("the helper should answer");
    helper.shutdown().expect("the helper should stop cleanly");

    assert!(
        !marker.exists(),
        "{} appeared while a unit was being analysed: the tree chose the program that ran",
        marker.display()
    );
    assert!(
        described.is_ok(),
        "a tree naming a program is still described: {described:?}"
    );
    assert_eq!(
        answer,
        Analysis::Missing(Unavailability::RequiresExecution),
        "the unit was read under a configuration this process had disabled"
    );
}

/// The other half: permitted, the tree's own build machinery is what runs,
/// which is what the permission is for.
#[test]
#[cfg(unix)]
fn permitting_execution_lets_the_tree_choose_its_wrapper() {
    let holder = tempfile::tempdir().expect("a temporary directory");
    let marker = holder.path().join("marker");
    let wrapper = wrapper_touching(&marker, holder.path());
    let tree = tree_building_a_script(&wrapper);

    let mut helper = start_through(&helper_choosing_nothing(holder.path()))
        .permitting(vec![Execution::BuildScript]);
    let answer = helper
        .analyze(&tree.unit(), &[Capability::Types])
        .expect("the helper should answer");
    // Read before the helper stops, since a build that declined to run says so
    // on the stream and the marker alone cannot say why it is absent.
    let said = helper.diagnostics();
    helper.shutdown().expect("the helper should stop cleanly");

    assert!(
        matches!(answer, Analysis::Done(_)),
        "permitted, the unit is read rather than declined: {answer:?}"
    );
    assert!(
        marker.exists(),
        "{} is missing: the permission bought the tree nothing it asked for; the helper said {said:?}",
        marker.display()
    );
}

/// Refusing has to say which key it refused over, since the sentence is all a
/// run gets: the reason on the wire stands for every kind of execution.
#[test]
fn a_tree_that_names_a_program_is_declined_by_the_key_that_names_it() {
    let tree = tree_naming(Path::new("/nowhere/at/all/wrapper"));

    let mut helper = helper();
    let answer = helper
        .analyze(&tree.unit(), &[Capability::Types])
        .expect("the helper should answer");
    let explained = why_it_refused(&helper);
    helper.shutdown().expect("the helper should stop cleanly");

    assert_eq!(answer, Analysis::Missing(Unavailability::RequiresExecution));
    assert!(
        explained
            .iter()
            .any(|line| line.contains("build.rustc-wrapper")),
        "the refusal named no key: {explained:?}"
    );
}

/// What the helper printed while refusing the unit just asked about. The
/// stream is read by a thread of its own, so a line written before the answer
/// can arrive after it.
fn why_it_refused(helper: &Helper) -> Vec<String> {
    let deadline = std::time::Instant::now() + Duration::from_secs(30);
    loop {
        let said = helper.diagnostics();
        if !said.is_empty() || std::time::Instant::now() > deadline {
            return said;
        }
        std::thread::sleep(Duration::from_millis(10));
    }
}

/// A wrapper this process inherited is not run for the tree either.
///
/// Cargo reads one out of the environment as readily as out of a file, and the
/// environment a scan runs in is not a thing this program gets to inspect. What
/// it can do is say which compiler is run and that nothing is run around it,
/// which is settled here for a tree that names nothing at all.
#[test]
#[cfg(unix)]
fn a_wrapper_inherited_from_the_environment_is_not_run_for_the_tree() {
    let holder = tempfile::tempdir().expect("a temporary directory");
    let marker = holder.path().join("marker");
    let wrapper = wrapper_touching(&marker, holder.path());
    let tree = tree_starting_nothing();

    let mut helper = start_through(&helper_inheriting(&wrapper, holder.path()));
    let described = helper.describe(&tree.root);
    let answer = helper
        .analyze(&tree.unit(), &[Capability::Types])
        .expect("the helper should answer");
    helper.shutdown().expect("the helper should stop cleanly");

    assert!(
        !marker.exists(),
        "{} appeared: the wrapper this process inherited ran for the tree",
        marker.display()
    );
    assert!(described.is_ok(), "{described:?}");
    assert!(
        matches!(answer, Analysis::Done(_)),
        "the tree became unreadable rather than readable without the wrapper: {answer:?}"
    );
}

/// And a configuration that starts nothing is not a reason to decline: a tree
/// that only says where its build output goes is read like any other.
#[test]
fn a_configuration_that_starts_nothing_leaves_the_tree_readable() {
    let tree = tree_starting_nothing();

    let mut helper = helper();
    let answer = helper
        .analyze(&tree.unit(), &[Capability::Types])
        .expect("the helper should answer");
    helper.shutdown().expect("the helper should stop cleanly");

    assert!(
        matches!(answer, Analysis::Done(_)),
        "a tree that names no program was declined: {answer:?}"
    );
}
