//! A package with both `src/lib.rs` and `src/main.rs` builds two crates under
//! one name, and a request has to be answered by the one that holds its file.

use super::*;

/// A package whose binary has a module the library does not.
fn library_and_binary_package() -> tempfile::TempDir {
    let directory = tempfile::tempdir().expect("a scratch directory");
    let root = directory.path();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"dual\"\nversion = \"0.1.0\"\nedition = \"2021\"\npublish = false\n",
    )
    .unwrap();
    // The helper resolves metadata with `--locked`, so the lock file has to
    // exist already.
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"dual\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn from_library() -> u32 { 1 }\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/main.rs"),
        "mod cli;\nfn from_binary() -> u32 { cli::from_binary_module() }\nfn main() { let _ = from_binary(); }\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/cli.rs"),
        "pub fn from_binary_module() -> u32 { 2 }\n",
    )
    .unwrap();
    directory
}

fn dual_unit(root: &Path, file: &str) -> UnitRef {
    UnitRef {
        unit: "dual".to_string(),
        file: root.join(file).display().to_string(),
        variant: "host".to_string(),
    }
}

#[test]
fn each_file_is_answered_by_the_crate_that_holds_it() {
    let package = library_and_binary_package();
    let root = package.path();
    let mut helper = helper();
    let mut declared = |file: &str, name: &str| {
        let Analysis::Done(ir) = helper
            .analyze(&dual_unit(root, file), &Capability::ALL)
            .expect("the helper should answer")
        else {
            panic!(
                "{file} was declined: {:?}",
                helper.take_answer_diagnostics()
            );
        };
        ir.symbols
            .iter()
            // A declaration carries its resolved type; a mention of the name
            // does not, and is reported whichever crate answered.
            .any(|symbol| {
                symbol.name == name
                    && symbol.kind == SymbolKind::Function
                    && symbol.type_index.is_some()
            })
    };

    assert!(declared("src/lib.rs", "from_library"));
    assert!(declared("src/main.rs", "from_binary"));
    assert!(declared("src/cli.rs", "from_binary_module"));
}
